#!/usr/bin/env python3
"""Generate the boxed-number PXT ABI layer from the primitive TypeScript API."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
TYPES = {
    "number": ("double", "TNumber"),
    "BodyType": ("double", "TNumber"),
    "BodyFlag": ("double", "TNumber"),
    "box2d.BodyType": ("double", "TNumber"),
    "box2d.BodyFlag": ("double", "TNumber"),
    "boolean": ("bool", "bool"),
    "number[]": ("RefCollection*", "RefCollection*"),
    "void": ("void", "void"),
}


def main():
    source = (ROOT / "main.ts").read_text()
    functions = re.findall(
        r"//(?:% shim=| Native wrapper: )box2dNative::(\w+)\s+export function (\w+)\(([^)]*)\): ([\w\[\]]+) \{",
        source,
    )
    if not functions:
        raise RuntimeError("No primitive bindings found")
    header = [
        "// Generated by tools/generate-bindings.py; do not edit.",
        "#pragma once",
        '#include "pxt.h"',
        "",
        "namespace box2d_native {",
        "using namespace pxt;",
    ]
    cpp = [
        "// Generated by tools/generate-bindings.py; do not edit.",
        '#include "native-api.h"',
        "",
        "using namespace pxt;",
        "",
        "namespace box2dNative {",
        "",
        "static double argument(RefCollection *args, int index) {",
        "    return toDouble(Array_::getAt(args, index));",
        "}",
        "",
        "static bool booleanArgument(RefCollection *args, int index) {",
        "    double value = argument(args, index);",
        "    if (value != 0 && value != 1) target_panic(906);",
        "    return value != 0;",
        "}",
    ]
    declarations = [
        "// Generated by tools/generate-bindings.py; do not edit.",
        "// Internal primitive bindings; public functions in main.ts supply defaults and packing.",
        "declare namespace box2dNativeShim {",
    ]
    for shim, name, parameters, result in functions:
        if shim != name:
            raise RuntimeError(f"Unexpected shim name: {shim}")
        native_parameters = []
        shim_parameters = []
        declaration_parameters = []
        arguments = []
        packed = len(parameters.split(",")) > 4
        for index, parameter in enumerate(parameters.split(",")):
            arg_name, declaration = parameter.strip().split(":", 1)
            ts_type = declaration.split("=", 1)[0].strip()
            native_type, shim_type = TYPES[ts_type]
            native_parameters.append(f"{native_type} {arg_name}")
            shim_parameters.append(f"{shim_type} {arg_name}")
            declaration_type = "number" if ts_type in ("BodyType", "BodyFlag", "box2d.BodyType", "box2d.BodyFlag") else ts_type
            declaration_parameters.append(f"{arg_name}: {declaration_type}")
            if packed:
                if ts_type == "number[]":
                    raise RuntimeError("Packed calls must contain only scalar arguments")
                helper = "booleanArgument" if ts_type == "boolean" else "argument"
                arguments.append(f"{helper}(args, {index})")
            else:
                arguments.append(f"toDouble({arg_name})" if shim_type == "TNumber" else arg_name)
        native_result, shim_result = TYPES[result]
        header.append(f"{native_result} {name}({', '.join(native_parameters)});")
        parameters_text = "RefCollection *args" if packed else ", ".join(shim_parameters)
        cpp += ["", "//%", f"{shim_result} {name}({parameters_text}) {{"]
        if packed:
            cpp.append(f"    if (!args || Array_::length(args) != {len(arguments)}) target_panic(906);")
        declaration_text = "args: number[]" if packed else ", ".join(declaration_parameters)
        declarations += [
            "",
            f"    //% shim=box2dNative::{name}",
            f"    function {name}({declaration_text}): {result};",
        ]
        call = f"box2d_native::{name}({', '.join(arguments)})"
        if result == "number":
            cpp.append(f"    return fromDouble({call});")
        elif result == "void":
            cpp.append(f"    {call};")
        else:
            cpp.append(f"    return {call};")
        cpp.append("}")
    header += ["} // namespace box2d_native", ""]
    cpp += ["", "} // namespace box2dNative", ""]
    declarations += ["}", ""]
    (ROOT / "native-api.h").write_text("\n".join(header))
    (ROOT / "bindings.cpp").write_text("\n".join(cpp))
    (ROOT / "packed.d.ts").write_text("\n".join(declarations))


if __name__ == "__main__":
    main()
