#include "jdlow.h"

#include <string.h>

//#define LOG(msg, ...) DMESG("JD: " msg, ##__VA_ARGS__)
#define LOG(...) ((void)0)

#define ERROR(msg, ...)                                                                            \
    do {                                                                                           \
        signal_error();                                                                            \
        DMESG("JD-ERROR: " msg, ##__VA_ARGS__);                                                    \
    } while (0)

#define RAM_FUNC __attribute__((noinline, long_call, section(".data")))

#define JD_STATUS_RX_ACTIVE 0x01
#define JD_STATUS_TX_ACTIVE 0x02
#define JD_STATUS_TX_QUEUED 0x04

static jd_serial_packet_t _rxBuffer[2];
static jd_serial_packet_t *rxPkt = &_rxBuffer[0];
static void set_tick_timer(uint8_t statusClear);
static volatile uint8_t status;

static jd_packet_t *txPkt;
static uint64_t nextAnnounce;
static uint8_t txPending;
static uint8_t annCounter;

static jd_diagnostics_t jd_diagnostics;

jd_diagnostics_t *jd_get_diagnostics(void) {
    jd_diagnostics.bus_state = 0; // TODO?
    return &jd_diagnostics;
}

static void pulse1() {
    log_pin_set(1, 1);
    log_pin_set(1, 0);
}

static void signal_error() {
    log_pin_set(2, 1);
    log_pin_set(2, 0);
}

static void signal_write(int v) {
    log_pin_set(4, v);
}

static void signal_read(int v) {
    // log_pin_set(0, v);
}
static void pulse_log_pin() {}

static void check_announce() {
    if (tim_get_micros() > nextAnnounce) {
        // pulse_log_pin();
        if (nextAnnounce)
            app_queue_annouce();
        nextAnnounce = tim_get_micros() + jd_random_around(400000);
    }
}

void jd_init() {
    DMESG("JD: init");
    tim_init();
    set_tick_timer(0);
    uart_init();
    check_announce();
}

int jd_is_running() {
    return nextAnnounce != 0;
}

static void tx_done() {
    signal_write(0);
    set_tick_timer(JD_STATUS_TX_ACTIVE);
}

void jd_tx_completed(int errCode) {
    LOG("tx done: %d", errCode);
    app_packet_sent(txPkt);
    txPkt = NULL;
    tx_done();
}

static void tick() {
    check_announce();
    set_tick_timer(0);
}

static void flush_tx_queue() {
    // pulse1();
    if (annCounter++ == 0)
        check_announce();

    LOG("flush %d", status);
    target_disable_irq();
    if (status & (JD_STATUS_RX_ACTIVE | JD_STATUS_TX_ACTIVE)) {
        target_enable_irq();
        return;
    }
    status |= JD_STATUS_TX_ACTIVE;
    target_enable_irq();

    txPending = 0;
    if (!txPkt)
        txPkt = app_pull_packet();

    signal_write(1);
    if (uart_start_tx(txPkt, JD_PACKET_SIZE(txPkt)) < 0) {
        // ERROR("race on TX");
        jd_diagnostics.bus_lo_error++;
        tx_done();
        txPending = 1;
        return;
    }

    set_tick_timer(0);
}

static void set_tick_timer(uint8_t statusClear) {
    target_disable_irq();
    if (statusClear) {
        // LOG("st %d @%d", statusClear, status);
        status &= ~statusClear;
    }
    if ((status & JD_STATUS_RX_ACTIVE) == 0) {
        if (txPending && !(status & JD_STATUS_TX_ACTIVE)) {
            pulse1();
            // the JD_WR_OVERHEAD value should be such, that the time from pulse1() above
            // to beginning of low-pulse generated by the current device is exactly 150us
            // (when the line below is uncommented)
            // tim_set_timer(150 - JD_WR_OVERHEAD, flush_tx_queue);
            status |= JD_STATUS_TX_QUEUED;
            tim_set_timer(jd_random_around(150) - JD_WR_OVERHEAD, flush_tx_queue);
        } else {
            status &= ~JD_STATUS_TX_QUEUED;
            tim_set_timer(10000, tick);
        }
    }
    target_enable_irq();
}

static void rx_timeout() {
    target_disable_irq();
    jd_diagnostics.bus_timeout_error++;
    ERROR("RX timeout");
    uart_disable();
    signal_read(0);
    set_tick_timer(JD_STATUS_RX_ACTIVE);
    target_enable_irq();
    signal_error();
}

static void setup_rx_timeout() {
    uint32_t *p = (uint32_t *)rxPkt;
    if (p[0] == 0 && p[1] == 0)
        rx_timeout(); // didn't get any data after lo-pulse
    // got the size - set timeout for whole packet
    tim_set_timer(JD_PACKET_SIZE(&rxPkt->header) * 12 + 60, rx_timeout);
}

void jd_line_falling() {
    LOG("line fall");
    pulse1();
    pulse_log_pin();
    signal_read(1);

    // target_disable_irq();
    // no need to disable IRQ - we're at the highest IRQ level
    if (status & JD_STATUS_RX_ACTIVE)
        jd_panic();
    status |= JD_STATUS_RX_ACTIVE;

    // 1us faster than memset() on SAMD21
    uint32_t *p = (uint32_t *)rxPkt;
    p[0] = 0;
    p[1] = 0;
    p[2] = 0;
    p[3] = 0;

    // otherwise we can enable RX in the middle of LO pulse
    uart_wait_high();
    // pulse1();
    // target_wait_us(2);

    pulse1();
    uart_start_rx(rxPkt, sizeof(*rxPkt));
    pulse1();

    tim_set_timer(100, setup_rx_timeout);

    // target_enable_irq();
}

void jd_rx_completed(int dataLeft) {
    if (annCounter++ == 0)
        check_announce();

    LOG("rx cmpl");
    jd_serial_packet_t *pkt = rxPkt;

    if (rxPkt == &_rxBuffer[0])
        rxPkt = &_rxBuffer[1];
    else
        rxPkt = &_rxBuffer[0];

    signal_read(0);
    set_tick_timer(JD_STATUS_RX_ACTIVE);

    if (dataLeft < 0) {
        ERROR("rx error: %d", dataLeft);
        jd_diagnostics.bus_uart_error++;
        return;
    }

    uint32_t txSize = sizeof(*pkt) - dataLeft;
    uint32_t declaredSize = JD_PACKET_SIZE(&pkt->header);
    if (txSize < declaredSize) {
        ERROR("pkt too short");
        jd_diagnostics.bus_uart_error++;
        return;
    }
    uint16_t crc = jd_crc16((uint8_t *)pkt + 2, declaredSize - 2);
    if (crc != pkt->header.crc) {
        ERROR("crc mismatch");
        jd_diagnostics.bus_uart_error++;
        return;
    }

    jd_diagnostics.packets_received++;

    // pulse1();
    int err = app_handle_packet(&pkt->header);

    if (err)
        jd_diagnostics.packets_dropped++;
}

void jd_compute_crc(jd_packet_t *pkt) {
    pkt->crc = jd_crc16((uint8_t *)pkt + 2, JD_PACKET_SIZE(pkt) - 2);
}

void jd_packet_ready() {
    target_disable_irq();
    txPending = 1;
    if (status == 0)
        set_tick_timer(0);
    target_enable_irq();
}

int jd_shift_frame(jd_packet_t *pkt) {
    int psize = pkt->_size;
    int oldsz = pkt->service_size;
    if (oldsz >= psize)
        return 0; // nothing to shift

    int ptr;
    if (pkt->data[oldsz] == 0xff) {
        ptr = pkt->data[oldsz + 1];
        if (ptr >= psize)
            return 0; // End-of-frame
        if (ptr <= oldsz)
            return 0; // don't let it go back, must be some corruption
    } else {
        ptr = oldsz;
    }

    uint8_t *src = &pkt->data[ptr];
    int newsz = *src + 4;
    if (ptr + newsz > pkt->_size) {
        ERROR("invalid super-frame");
        return 0;
    }
    uint8_t *dst = &pkt->service_size;
    // don't trust memmove()
    for (int i = 0; i < newsz; ++i)
        *dst++ = *src++;
    // store ptr
    ptr += newsz;
    pkt->data[newsz - 4] = 0xff;
    pkt->data[newsz - 4 + 1] = ptr;

    return 1;
}
