#include "jdlow.h"

#include <string.h>

//#define LOG(msg, ...) DMESG("JD: " msg, ##__VA_ARGS__)
#define LOG(...) ((void)0)

#define ERROR(msg, ...)                                                                            \
    do {                                                                                           \
        signal_error();                                                                            \
        DMESG("JD-ERROR: " msg, ##__VA_ARGS__);                                                    \
    } while (0)

#define RAM_FUNC __attribute__((noinline, long_call, section(".data")))

#define JD_STATUS_RX_ACTIVE 0x01
#define JD_STATUS_TX_ACTIVE 0x02

static jd_serial_packet_t _rxBuffer[2];
static jd_serial_packet_t *rxPkt = &_rxBuffer[0];
static void set_tick_timer(uint8_t statusClear);
static uint64_t nextAnnounce;
static volatile uint8_t status;
static volatile uint8_t numPending;
static uint8_t annCounter;

static jd_diagnostics_t jd_diagnostics;

jd_diagnostics_t *jd_get_diagnostics(void) {
    jd_diagnostics.bus_state = 0; // TODO?
    return &jd_diagnostics;
}

static jd_packet_t *txQueue[JD_TX_QUEUE_SIZE];
static uint8_t crcAckPtr;
static uint16_t crcAcks[JD_CRC_QUEUE_SIZE];
static jd_packet_t crcPkt;

static void pulse1() {
    log_pin_set(1, 1);
    log_pin_set(1, 0);
}

static void signal_error() {
    log_pin_set(2, 1);
    log_pin_set(2, 0);
}

static void signal_write(int v) {
    log_pin_set(4, v);
}

static void signal_read(int v) {
    // log_pin_set(0, v);
}
static void pulse_log_pin() {}

static void check_announce() {
    if (tim_get_micros() > nextAnnounce) {
        // pulse_log_pin();
        if (nextAnnounce)
            app_queue_annouce();
        nextAnnounce = tim_get_micros() + jd_random_around(400000);
    }
}

void jd_init() {
    DMESG("JD: init");
    tim_init();
    set_tick_timer(0);
    uart_init();
    check_announce();
}

int jd_is_running() {
    return nextAnnounce != 0;
}

static void tx_done() {
    signal_write(0);
    set_tick_timer(JD_STATUS_TX_ACTIVE);
}

static void shift_queue() {
    target_disable_irq();
    for (int i = 1; i < JD_TX_QUEUE_SIZE; ++i)
        txQueue[i - 1] = txQueue[i];
    txQueue[JD_TX_QUEUE_SIZE - 1] = 0;
    target_enable_irq();
}

void jd_tx_completed(int errCode) {
    LOG("tx done: %d", errCode);
    if (numPending == 0)
        jd_panic();
    target_disable_irq();
    jd_packet_t *prev = txQueue[0];
    shift_queue();
    numPending--;
    target_enable_irq();
    app_packet_sent(prev);
    tx_done();
}

uint32_t jd_get_num_pending_tx() {
    return numPending;
}

uint32_t jd_get_free_queue_space() {
    for (int i = JD_TX_QUEUE_SIZE - 1; i >= 0; ++i) {
        if (txQueue[i])
            return JD_TX_QUEUE_SIZE - i - 1;
    }
    return 0;
}

static void tick() {
    check_announce();
    set_tick_timer(0);
}

static void flush_tx_queue() {
    //pulse1();
    if (annCounter++ == 0)
        check_announce();

    LOG("flush %d", status);
    target_disable_irq();
    if (status & (JD_STATUS_RX_ACTIVE | JD_STATUS_TX_ACTIVE)) {
        target_enable_irq();
        return;
    }
    status |= JD_STATUS_TX_ACTIVE;
    jd_packet_t *pkt = txQueue[0];
    if (crcAckPtr) {
        pkt = &crcPkt;
        crcPkt.service_arg = crcAcks[0];
    }
    target_enable_irq();

    signal_write(1);
    if (uart_start_tx(pkt, pkt->size + JD_SERIAL_FULL_HEADER_SIZE) < 0) {
        // ERROR("race on TX");
        jd_diagnostics.bus_lo_error++;
        tx_done();
        return;
    }

    if (pkt == &crcPkt) {
        target_disable_irq();
        for (int i = 1; i < crcAckPtr; ++i)
            crcAcks[i - 1] = crcAcks[i];
        crcAckPtr--;
        target_enable_irq();
    }

    set_tick_timer(0);
}

static void push_crc(uint16_t crc) {
    target_disable_irq();
    if (crcAckPtr < JD_CRC_QUEUE_SIZE)
        crcAcks[crcAckPtr++] = crc;
    target_enable_irq();
}

static void set_tick_timer(uint8_t statusClear) {
    target_disable_irq();
    if (statusClear) {
        // LOG("st %d @%d", statusClear, status);
        status &= ~statusClear;
    }
    if ((status & JD_STATUS_RX_ACTIVE) == 0) {
        if ((crcAckPtr || txQueue[0]) && !(status & JD_STATUS_TX_ACTIVE)) {
            pulse1();
            // the JD_WR_OVERHEAD value should be such, that the time from pulse1() above
            // to beginning of low-pulse generated by us is exactly 150us (when the line
            // below is uncommented)
            //tim_set_timer(150 - JD_WR_OVERHEAD, flush_tx_queue);
            tim_set_timer(jd_random_around(150) - JD_WR_OVERHEAD, flush_tx_queue);
        } else
            tim_set_timer(10000, tick);
    }
    target_enable_irq();
}

static void rx_timeout() {
    target_disable_irq();
    jd_diagnostics.bus_timeout_error++;
    ERROR("RX timeout");
    uart_disable();
    signal_read(0);
    set_tick_timer(JD_STATUS_RX_ACTIVE);
    target_enable_irq();
    signal_error();
}

static void setup_rx_timeout() {
    uint32_t *p = (uint32_t *)rxPkt;
    if (p[0] == 0 && p[1] == 0)
        rx_timeout(); // didn't get any data after lo-pulse
    // got the size - set timeout for whole packet
    tim_set_timer((rxPkt->header.size + JD_SERIAL_FULL_HEADER_SIZE) * 12 + 60, rx_timeout);
}

void jd_line_falling() {
    LOG("line fall");
    pulse1();
    pulse_log_pin();
    signal_read(1);
    // target_disable_irq();
    if (status & JD_STATUS_RX_ACTIVE)
        jd_panic();
    status |= JD_STATUS_RX_ACTIVE;

#if 1
    // 1us faster on SAMD21
    uint32_t *p = (uint32_t *)rxPkt;
    p[0] = 0;
    p[1] = 0;
    p[2] = 0;
    p[3] = 0;
#else
    memset(rxPkt, 0, JD_SERIAL_FULL_HEADER_SIZE);
#endif

    // otherwise we can enable RX in the middle of LO pulse
    uart_wait_high();
    // pulse1();
    // target_wait_us(2);

    pulse1();
    uart_start_rx(rxPkt, sizeof(*rxPkt));
    pulse1();

    tim_set_timer(100, setup_rx_timeout);

    // target_enable_irq();
}

void jd_rx_completed(int dataLeft) {
    if (annCounter++ == 0)
        check_announce();

    LOG("rx cmpl");
    jd_serial_packet_t *pkt = rxPkt;

    if (rxPkt == &_rxBuffer[0])
        rxPkt = &_rxBuffer[1];
    else
        rxPkt = &_rxBuffer[0];

    signal_read(0);
    set_tick_timer(JD_STATUS_RX_ACTIVE);

    if (dataLeft < 0) {
        ERROR("rx error: %d", dataLeft);
        jd_diagnostics.bus_uart_error++;
        return;
    }

    uint32_t txSize = sizeof(*pkt) - dataLeft;
    uint32_t declaredSize = pkt->header.size + JD_SERIAL_FULL_HEADER_SIZE;
    if (txSize < declaredSize) {
        ERROR("pkt too short");
        jd_diagnostics.bus_uart_error++;
        return;
    }
    uint16_t crc = jd_crc16((uint8_t *)pkt + 2, declaredSize - 2);
    if (crc != pkt->header.crc) {
        ERROR("crc mismatch");
        jd_diagnostics.bus_uart_error++;
        return;
    }

#if 0
    // this can be correct
    if (crc == 0) {
        ERROR("crc==0");
        jd_diagnostics.bus_uart_error++;
        return;
    }
#endif

    jd_diagnostics.packets_received++;

    // pulse1();
    int err = app_handle_packet(&pkt->header);

    if (err) {
        jd_diagnostics.packets_dropped++;
        return;
    }

    // only ack when requested and only to packets addressed to us
    if ((pkt->header.service_number & JD_SERVICE_NUMBER_REQUIRES_ACK) &&
        crcPkt.service_command && // crcPkt initialized
        crcPkt.device_identifier == pkt->header.device_identifier)
        push_crc(pkt->header.crc);
}

void jd_compute_crc(jd_packet_t *pkt) {
    uint32_t declaredSize = pkt->size + JD_SERIAL_FULL_HEADER_SIZE;
    pkt->crc = jd_crc16((uint8_t *)pkt + 2, declaredSize - 2);
}

int jd_queue_packet(jd_packet_t *pkt) {
    if (!pkt)
        return -2;

    jd_compute_crc(pkt);
    int queued = 0;

    target_disable_irq();
    if (numPending < JD_TX_QUEUE_SIZE) {
        txQueue[numPending++] = pkt;
        queued = 1;
    }
    target_enable_irq();

    // is it announce packet, and we didn't initalize crcPkt yet?
    if (!crcPkt.service_command && pkt->service_number == 0 && pkt->service_command == 0) {
        crcPkt.service_command = 1;
        crcPkt.device_identifier = pkt->device_identifier;
    }

    if (!queued) {
        // codal counts packet dropped on recv, this is sent; we never hit that
        jd_diagnostics.packets_dropped++;
        app_packet_dropped(pkt);
        ERROR("TX overflow");
        return -1;
    }

    set_tick_timer(0);
    return 0;
}
