// Generated by tools/generate-bindings.py; do not edit.
#include "native-api.h"

using namespace pxt;

namespace box2dNative {

static double argument(RefCollection *args, int index) {
    return toDouble(Array_::getAt(args, index));
}

static bool booleanArgument(RefCollection *args, int index) {
    double value = argument(args, index);
    if (value != 0 && value != 1) target_panic(906);
    return value != 0;
}

static Box2DObject objectArgument(RefCollection *args, int index) {
    return (Box2DObject)(uintptr_t)Array_::getAt(args, index);
}

//%
Box2DObject createWorld(TNumber gravityX, TNumber gravityY) {
    return box2d_native::createWorld(toDouble(gravityX), toDouble(gravityY));
}

//%
void destroyWorld(Box2DObject world) {
    box2d_native::destroyWorld(world);
}

//%
bool isValid(Box2DObject handle) {
    return box2d_native::isValid(handle);
}

//%
void setGravity(Box2DObject world, TNumber x, TNumber y) {
    box2d_native::setGravity(world, toDouble(x), toDouble(y));
}

//%
void step(Box2DObject world, TNumber seconds, TNumber velocityIterations, TNumber positionIterations) {
    box2d_native::step(world, toDouble(seconds), toDouble(velocityIterations), toDouble(positionIterations));
}

//%
void setWorldSleepingAllowed(Box2DObject world, bool allowed) {
    box2d_native::setWorldSleepingAllowed(world, allowed);
}

//%
Box2DObject createBody(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::createBody(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

//%
void destroyBody(Box2DObject body) {
    box2d_native::destroyBody(body);
}

//%
RefCollection* getBodyState(Box2DObject body) {
    return box2d_native::getBodyState(body);
}

//%
void readBodyTransform(Box2DObject body, RefCollection* output) {
    box2d_native::readBodyTransform(body, output);
}

//%
void readBodyBoxVertices(Box2DObject body, RefCollection* box, RefCollection* view, RefCollection* output) {
    box2d_native::readBodyBoxVertices(body, box, view, output);
}

//%
void setTransform(Box2DObject body, TNumber x, TNumber y, TNumber angle) {
    box2d_native::setTransform(body, toDouble(x), toDouble(y), toDouble(angle));
}

//%
void setLinearVelocity(Box2DObject body, TNumber x, TNumber y) {
    box2d_native::setLinearVelocity(body, toDouble(x), toDouble(y));
}

//%
void setAngularVelocity(Box2DObject body, TNumber velocity) {
    box2d_native::setAngularVelocity(body, toDouble(velocity));
}

//%
void setBodyType(Box2DObject body, TNumber type) {
    box2d_native::setBodyType(body, toDouble(type));
}

//%
void setDamping(Box2DObject body, TNumber linear, TNumber angular) {
    box2d_native::setDamping(body, toDouble(linear), toDouble(angular));
}

//%
void setGravityScale(Box2DObject body, TNumber scale) {
    box2d_native::setGravityScale(body, toDouble(scale));
}

//%
void setBodyFlag(Box2DObject body, TNumber flag, bool enabled) {
    box2d_native::setBodyFlag(body, toDouble(flag), enabled);
}

//%
bool getBodyFlag(Box2DObject body, TNumber flag) {
    return box2d_native::getBodyFlag(body, toDouble(flag));
}

//%
void applyForce(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::applyForce(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5));
}

//%
void applyForceToCenter(Box2DObject body, TNumber x, TNumber y, bool wake) {
    box2d_native::applyForceToCenter(body, toDouble(x), toDouble(y), wake);
}

//%
void applyLinearImpulse(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::applyLinearImpulse(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5));
}

//%
void applyLinearImpulseToCenter(Box2DObject body, TNumber x, TNumber y, bool wake) {
    box2d_native::applyLinearImpulseToCenter(body, toDouble(x), toDouble(y), wake);
}

//%
void applyTorque(Box2DObject body, TNumber torque, bool wake) {
    box2d_native::applyTorque(body, toDouble(torque), wake);
}

//%
void applyAngularImpulse(Box2DObject body, TNumber impulse, bool wake) {
    box2d_native::applyAngularImpulse(body, toDouble(impulse), wake);
}

//%
RefCollection* getWorldPoint(Box2DObject body, TNumber x, TNumber y) {
    return box2d_native::getWorldPoint(body, toDouble(x), toDouble(y));
}

//%
RefCollection* getLocalPoint(Box2DObject body, TNumber x, TNumber y) {
    return box2d_native::getLocalPoint(body, toDouble(x), toDouble(y));
}

//%
Box2DObject createCircleShape(TNumber radius, TNumber centerX, TNumber centerY) {
    return box2d_native::createCircleShape(toDouble(radius), toDouble(centerX), toDouble(centerY));
}

//%
Box2DObject createBoxShape(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::createBoxShape(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

//%
Box2DObject createPolygonShape(RefCollection* vertices) {
    return box2d_native::createPolygonShape(vertices);
}

//%
Box2DObject createEdgeShape(TNumber x1, TNumber y1, TNumber x2, TNumber y2) {
    return box2d_native::createEdgeShape(toDouble(x1), toDouble(y1), toDouble(x2), toDouble(y2));
}

//%
Box2DObject createChainShape(RefCollection* vertices, bool loop) {
    return box2d_native::createChainShape(vertices, loop);
}

//%
void destroyShape(Box2DObject shape) {
    box2d_native::destroyShape(shape);
}

//%
Box2DObject createFixture(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    return box2d_native::createFixture(objectArgument(args, 0), objectArgument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5));
}

//%
void destroyFixture(Box2DObject fixture) {
    box2d_native::destroyFixture(fixture);
}

//%
Box2DObject getFixtureBody(Box2DObject fixture) {
    return box2d_native::getFixtureBody(fixture);
}

//%
void setFixtureMaterial(Box2DObject fixture, TNumber density, TNumber friction, TNumber restitution) {
    box2d_native::setFixtureMaterial(fixture, toDouble(density), toDouble(friction), toDouble(restitution));
}

//%
void setFixtureSensor(Box2DObject fixture, bool sensor) {
    box2d_native::setFixtureSensor(fixture, sensor);
}

//%
void setFixtureFilter(Box2DObject fixture, TNumber categoryBits, TNumber maskBits, TNumber groupIndex) {
    box2d_native::setFixtureFilter(fixture, toDouble(categoryBits), toDouble(maskBits), toDouble(groupIndex));
}

//%
bool testPoint(Box2DObject fixture, TNumber x, TNumber y) {
    return box2d_native::testPoint(fixture, toDouble(x), toDouble(y));
}

//%
Box2DObject createDistanceJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return box2d_native::createDistanceJoint(objectArgument(args, 0), objectArgument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), booleanArgument(args, 6));
}

//%
void setDistanceJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::setDistanceJoint(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5));
}

//%
Box2DObject createRevoluteJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::createRevoluteJoint(objectArgument(args, 0), objectArgument(args, 1), argument(args, 2), argument(args, 3), booleanArgument(args, 4));
}

//%
void setRevoluteJointMotor(Box2DObject joint, bool enabled, TNumber speed, TNumber maxTorque) {
    box2d_native::setRevoluteJointMotor(joint, enabled, toDouble(speed), toDouble(maxTorque));
}

//%
void setRevoluteJointLimits(Box2DObject joint, bool enabled, TNumber lower, TNumber upper) {
    box2d_native::setRevoluteJointLimits(joint, enabled, toDouble(lower), toDouble(upper));
}

//%
Box2DObject createWheelJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return box2d_native::createWheelJoint(objectArgument(args, 0), objectArgument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), booleanArgument(args, 6));
}

//%
void setWheelJointMotor(Box2DObject joint, bool enabled, TNumber speed, TNumber maxTorque) {
    box2d_native::setWheelJointMotor(joint, enabled, toDouble(speed), toDouble(maxTorque));
}

//%
void setWheelJointLimits(Box2DObject joint, bool enabled, TNumber lower, TNumber upper) {
    box2d_native::setWheelJointLimits(joint, enabled, toDouble(lower), toDouble(upper));
}

//%
void setWheelJointSuspension(Box2DObject joint, TNumber stiffness, TNumber damping) {
    box2d_native::setWheelJointSuspension(joint, toDouble(stiffness), toDouble(damping));
}

//%
Box2DObject createMouseJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return box2d_native::createMouseJoint(objectArgument(args, 0), objectArgument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), argument(args, 6));
}

//%
void setMouseJointTarget(Box2DObject joint, TNumber x, TNumber y) {
    box2d_native::setMouseJointTarget(joint, toDouble(x), toDouble(y));
}

//%
void destroyJoint(Box2DObject joint) {
    box2d_native::destroyJoint(joint);
}

//%
RefCollection* getContacts(Box2DObject world) {
    return box2d_native::getContacts(world);
}

//%
RefCollection* queryAABB(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::queryAABB(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

//%
RefCollection* rayCast(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::rayCast(objectArgument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

} // namespace box2dNative
