// Generated by tools/generate-bindings.py; do not edit.
#include "native-api.h"

using namespace pxt;

namespace box2dNative {

static double argument(RefCollection *args, int index) {
    return toDouble(Array_::getAt(args, index));
}

static bool booleanArgument(RefCollection *args, int index) {
    double value = argument(args, index);
    if (value != 0 && value != 1) target_panic(906);
    return value != 0;
}

//%
TNumber createWorld(TNumber gravityX, TNumber gravityY) {
    return fromDouble(box2d_native::createWorld(toDouble(gravityX), toDouble(gravityY)));
}

//%
void destroyWorld(TNumber world) {
    box2d_native::destroyWorld(toDouble(world));
}

//%
bool isValid(TNumber handle) {
    return box2d_native::isValid(toDouble(handle));
}

//%
void setGravity(TNumber world, TNumber x, TNumber y) {
    box2d_native::setGravity(toDouble(world), toDouble(x), toDouble(y));
}

//%
void step(TNumber world, TNumber seconds, TNumber velocityIterations, TNumber positionIterations) {
    box2d_native::step(toDouble(world), toDouble(seconds), toDouble(velocityIterations), toDouble(positionIterations));
}

//%
void setWorldSleepingAllowed(TNumber world, bool allowed) {
    box2d_native::setWorldSleepingAllowed(toDouble(world), allowed);
}

//%
TNumber createBody(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return fromDouble(box2d_native::createBody(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4)));
}

//%
void destroyBody(TNumber body) {
    box2d_native::destroyBody(toDouble(body));
}

//%
RefCollection* getBodyState(TNumber body) {
    return box2d_native::getBodyState(toDouble(body));
}

//%
void readBodyTransform(TNumber body, RefCollection* output) {
    box2d_native::readBodyTransform(toDouble(body), output);
}

//%
void readBodyBoxVertices(TNumber body, RefCollection* box, RefCollection* view, RefCollection* output) {
    box2d_native::readBodyBoxVertices(toDouble(body), box, view, output);
}

//%
void setTransform(TNumber body, TNumber x, TNumber y, TNumber angle) {
    box2d_native::setTransform(toDouble(body), toDouble(x), toDouble(y), toDouble(angle));
}

//%
void setLinearVelocity(TNumber body, TNumber x, TNumber y) {
    box2d_native::setLinearVelocity(toDouble(body), toDouble(x), toDouble(y));
}

//%
void setAngularVelocity(TNumber body, TNumber velocity) {
    box2d_native::setAngularVelocity(toDouble(body), toDouble(velocity));
}

//%
void setBodyType(TNumber body, TNumber type) {
    box2d_native::setBodyType(toDouble(body), toDouble(type));
}

//%
void setDamping(TNumber body, TNumber linear, TNumber angular) {
    box2d_native::setDamping(toDouble(body), toDouble(linear), toDouble(angular));
}

//%
void setGravityScale(TNumber body, TNumber scale) {
    box2d_native::setGravityScale(toDouble(body), toDouble(scale));
}

//%
void setBodyFlag(TNumber body, TNumber flag, bool enabled) {
    box2d_native::setBodyFlag(toDouble(body), toDouble(flag), enabled);
}

//%
bool getBodyFlag(TNumber body, TNumber flag) {
    return box2d_native::getBodyFlag(toDouble(body), toDouble(flag));
}

//%
void applyForce(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::applyForce(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5));
}

//%
void applyForceToCenter(TNumber body, TNumber x, TNumber y, bool wake) {
    box2d_native::applyForceToCenter(toDouble(body), toDouble(x), toDouble(y), wake);
}

//%
void applyLinearImpulse(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::applyLinearImpulse(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5));
}

//%
void applyLinearImpulseToCenter(TNumber body, TNumber x, TNumber y, bool wake) {
    box2d_native::applyLinearImpulseToCenter(toDouble(body), toDouble(x), toDouble(y), wake);
}

//%
void applyTorque(TNumber body, TNumber torque, bool wake) {
    box2d_native::applyTorque(toDouble(body), toDouble(torque), wake);
}

//%
void applyAngularImpulse(TNumber body, TNumber impulse, bool wake) {
    box2d_native::applyAngularImpulse(toDouble(body), toDouble(impulse), wake);
}

//%
RefCollection* getWorldPoint(TNumber body, TNumber x, TNumber y) {
    return box2d_native::getWorldPoint(toDouble(body), toDouble(x), toDouble(y));
}

//%
RefCollection* getLocalPoint(TNumber body, TNumber x, TNumber y) {
    return box2d_native::getLocalPoint(toDouble(body), toDouble(x), toDouble(y));
}

//%
TNumber createCircleShape(TNumber radius, TNumber centerX, TNumber centerY) {
    return fromDouble(box2d_native::createCircleShape(toDouble(radius), toDouble(centerX), toDouble(centerY)));
}

//%
TNumber createBoxShape(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return fromDouble(box2d_native::createBoxShape(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4)));
}

//%
TNumber createPolygonShape(RefCollection* vertices) {
    return fromDouble(box2d_native::createPolygonShape(vertices));
}

//%
TNumber createEdgeShape(TNumber x1, TNumber y1, TNumber x2, TNumber y2) {
    return fromDouble(box2d_native::createEdgeShape(toDouble(x1), toDouble(y1), toDouble(x2), toDouble(y2)));
}

//%
TNumber createChainShape(RefCollection* vertices, bool loop) {
    return fromDouble(box2d_native::createChainShape(vertices, loop));
}

//%
void destroyShape(TNumber shape) {
    box2d_native::destroyShape(toDouble(shape));
}

//%
TNumber createFixture(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    return fromDouble(box2d_native::createFixture(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), booleanArgument(args, 5)));
}

//%
void destroyFixture(TNumber fixture) {
    box2d_native::destroyFixture(toDouble(fixture));
}

//%
TNumber getFixtureBody(TNumber fixture) {
    return fromDouble(box2d_native::getFixtureBody(toDouble(fixture)));
}

//%
void setFixtureMaterial(TNumber fixture, TNumber density, TNumber friction, TNumber restitution) {
    box2d_native::setFixtureMaterial(toDouble(fixture), toDouble(density), toDouble(friction), toDouble(restitution));
}

//%
void setFixtureSensor(TNumber fixture, bool sensor) {
    box2d_native::setFixtureSensor(toDouble(fixture), sensor);
}

//%
void setFixtureFilter(TNumber fixture, TNumber categoryBits, TNumber maskBits, TNumber groupIndex) {
    box2d_native::setFixtureFilter(toDouble(fixture), toDouble(categoryBits), toDouble(maskBits), toDouble(groupIndex));
}

//%
bool testPoint(TNumber fixture, TNumber x, TNumber y) {
    return box2d_native::testPoint(toDouble(fixture), toDouble(x), toDouble(y));
}

//%
TNumber createDistanceJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return fromDouble(box2d_native::createDistanceJoint(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), booleanArgument(args, 6)));
}

//%
void setDistanceJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 6) target_panic(906);
    box2d_native::setDistanceJoint(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5));
}

//%
TNumber createRevoluteJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return fromDouble(box2d_native::createRevoluteJoint(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), booleanArgument(args, 4)));
}

//%
void setRevoluteJointMotor(TNumber joint, bool enabled, TNumber speed, TNumber maxTorque) {
    box2d_native::setRevoluteJointMotor(toDouble(joint), enabled, toDouble(speed), toDouble(maxTorque));
}

//%
void setRevoluteJointLimits(TNumber joint, bool enabled, TNumber lower, TNumber upper) {
    box2d_native::setRevoluteJointLimits(toDouble(joint), enabled, toDouble(lower), toDouble(upper));
}

//%
TNumber createWheelJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return fromDouble(box2d_native::createWheelJoint(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), booleanArgument(args, 6)));
}

//%
void setWheelJointMotor(TNumber joint, bool enabled, TNumber speed, TNumber maxTorque) {
    box2d_native::setWheelJointMotor(toDouble(joint), enabled, toDouble(speed), toDouble(maxTorque));
}

//%
void setWheelJointLimits(TNumber joint, bool enabled, TNumber lower, TNumber upper) {
    box2d_native::setWheelJointLimits(toDouble(joint), enabled, toDouble(lower), toDouble(upper));
}

//%
void setWheelJointSuspension(TNumber joint, TNumber stiffness, TNumber damping) {
    box2d_native::setWheelJointSuspension(toDouble(joint), toDouble(stiffness), toDouble(damping));
}

//%
TNumber createMouseJoint(RefCollection *args) {
    if (!args || Array_::length(args) != 7) target_panic(906);
    return fromDouble(box2d_native::createMouseJoint(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4), argument(args, 5), argument(args, 6)));
}

//%
void setMouseJointTarget(TNumber joint, TNumber x, TNumber y) {
    box2d_native::setMouseJointTarget(toDouble(joint), toDouble(x), toDouble(y));
}

//%
void destroyJoint(TNumber joint) {
    box2d_native::destroyJoint(toDouble(joint));
}

//%
RefCollection* getContacts(TNumber world) {
    return box2d_native::getContacts(toDouble(world));
}

//%
RefCollection* queryAABB(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::queryAABB(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

//%
RefCollection* rayCast(RefCollection *args) {
    if (!args || Array_::length(args) != 5) target_panic(906);
    return box2d_native::rayCast(argument(args, 0), argument(args, 1), argument(args, 2), argument(args, 3), argument(args, 4));
}

} // namespace box2dNative
