// Generated by tools/generate-bindings.py; do not edit.
#pragma once
#include "pxt.h"

namespace box2d_native { class RefBox2D; }
using Box2DObject = box2d_native::RefBox2D*;

namespace box2d_native {
using namespace pxt;
RefBox2D* createWorld(double gravityX, double gravityY);
void destroyWorld(RefBox2D* world);
bool isValid(RefBox2D* handle);
void setGravity(RefBox2D* world, double x, double y);
void step(RefBox2D* world, double seconds, double velocityIterations, double positionIterations);
void setWorldSleepingAllowed(RefBox2D* world, bool allowed);
RefBox2D* createBody(RefBox2D* world, double type, double x, double y, double angle);
void destroyBody(RefBox2D* body);
RefCollection* getBodyState(RefBox2D* body);
void readBodyTransform(RefBox2D* body, RefCollection* output);
void readBodyBoxVertices(RefBox2D* body, RefCollection* box, RefCollection* view, RefCollection* output);
void setTransform(RefBox2D* body, double x, double y, double angle);
void setLinearVelocity(RefBox2D* body, double x, double y);
void setAngularVelocity(RefBox2D* body, double velocity);
void setBodyType(RefBox2D* body, double type);
void setDamping(RefBox2D* body, double linear, double angular);
void setGravityScale(RefBox2D* body, double scale);
void setBodyFlag(RefBox2D* body, double flag, bool enabled);
bool getBodyFlag(RefBox2D* body, double flag);
void applyForce(RefBox2D* body, double x, double y, double pointX, double pointY, bool wake);
void applyForceToCenter(RefBox2D* body, double x, double y, bool wake);
void applyLinearImpulse(RefBox2D* body, double x, double y, double pointX, double pointY, bool wake);
void applyLinearImpulseToCenter(RefBox2D* body, double x, double y, bool wake);
void applyTorque(RefBox2D* body, double torque, bool wake);
void applyAngularImpulse(RefBox2D* body, double impulse, bool wake);
RefCollection* getWorldPoint(RefBox2D* body, double x, double y);
RefCollection* getLocalPoint(RefBox2D* body, double x, double y);
RefBox2D* createCircleShape(double radius, double centerX, double centerY);
RefBox2D* createBoxShape(double halfWidth, double halfHeight, double centerX, double centerY, double angle);
RefBox2D* createPolygonShape(RefCollection* vertices);
RefBox2D* createEdgeShape(double x1, double y1, double x2, double y2);
RefBox2D* createChainShape(RefCollection* vertices, bool loop);
void destroyShape(RefBox2D* shape);
RefBox2D* createFixture(RefBox2D* body, RefBox2D* shape, double density, double friction, double restitution, bool sensor);
void destroyFixture(RefBox2D* fixture);
RefBox2D* getFixtureBody(RefBox2D* fixture);
void setFixtureMaterial(RefBox2D* fixture, double density, double friction, double restitution);
void setFixtureSensor(RefBox2D* fixture, bool sensor);
void setFixtureFilter(RefBox2D* fixture, double categoryBits, double maskBits, double groupIndex);
bool testPoint(RefBox2D* fixture, double x, double y);
RefBox2D* createDistanceJoint(RefBox2D* bodyA, RefBox2D* bodyB, double anchorAX, double anchorAY, double anchorBX, double anchorBY, bool collideConnected);
void setDistanceJoint(RefBox2D* joint, double length, double minLength, double maxLength, double stiffness, double damping);
RefBox2D* createRevoluteJoint(RefBox2D* bodyA, RefBox2D* bodyB, double anchorX, double anchorY, bool collideConnected);
void setRevoluteJointMotor(RefBox2D* joint, bool enabled, double speed, double maxTorque);
void setRevoluteJointLimits(RefBox2D* joint, bool enabled, double lower, double upper);
RefBox2D* createWheelJoint(RefBox2D* bodyA, RefBox2D* bodyB, double anchorX, double anchorY, double axisX, double axisY, bool collideConnected);
void setWheelJointMotor(RefBox2D* joint, bool enabled, double speed, double maxTorque);
void setWheelJointLimits(RefBox2D* joint, bool enabled, double lower, double upper);
void setWheelJointSuspension(RefBox2D* joint, double stiffness, double damping);
RefBox2D* createMouseJoint(RefBox2D* bodyA, RefBox2D* bodyB, double anchorX, double anchorY, double maxForce, double stiffness, double damping);
void setMouseJointTarget(RefBox2D* joint, double x, double y);
RefCollection* getJointAnchors(RefBox2D* joint);
void destroyJoint(RefBox2D* joint);
RefCollection* getContacts(RefBox2D* world);
RefCollection* queryAABB(RefBox2D* world, double minX, double minY, double maxX, double maxY);
RefCollection* rayCast(RefBox2D* world, double x1, double y1, double x2, double y2);
} // namespace box2d_native
