// Generated by tools/generate-bindings.py; do not edit.
#pragma once
#include "pxt.h"

namespace box2d_native {
using namespace pxt;
double createWorld(double gravityX, double gravityY);
void destroyWorld(double world);
bool isValid(double handle);
void setGravity(double world, double x, double y);
void step(double world, double seconds, double velocityIterations, double positionIterations);
void setWorldSleepingAllowed(double world, bool allowed);
double createBody(double world, double type, double x, double y, double angle);
void destroyBody(double body);
RefCollection* getBodyState(double body);
void readBodyTransform(double body, RefCollection* output);
void readBodyBoxVertices(double body, RefCollection* box, RefCollection* view, RefCollection* output);
void setTransform(double body, double x, double y, double angle);
void setLinearVelocity(double body, double x, double y);
void setAngularVelocity(double body, double velocity);
void setBodyType(double body, double type);
void setDamping(double body, double linear, double angular);
void setGravityScale(double body, double scale);
void setBodyFlag(double body, double flag, bool enabled);
bool getBodyFlag(double body, double flag);
void applyForce(double body, double x, double y, double pointX, double pointY, bool wake);
void applyForceToCenter(double body, double x, double y, bool wake);
void applyLinearImpulse(double body, double x, double y, double pointX, double pointY, bool wake);
void applyLinearImpulseToCenter(double body, double x, double y, bool wake);
void applyTorque(double body, double torque, bool wake);
void applyAngularImpulse(double body, double impulse, bool wake);
RefCollection* getWorldPoint(double body, double x, double y);
RefCollection* getLocalPoint(double body, double x, double y);
double createCircleShape(double radius, double centerX, double centerY);
double createBoxShape(double halfWidth, double halfHeight, double centerX, double centerY, double angle);
double createPolygonShape(RefCollection* vertices);
double createEdgeShape(double x1, double y1, double x2, double y2);
double createChainShape(RefCollection* vertices, bool loop);
void destroyShape(double shape);
double createFixture(double body, double shape, double density, double friction, double restitution, bool sensor);
void destroyFixture(double fixture);
double getFixtureBody(double fixture);
void setFixtureMaterial(double fixture, double density, double friction, double restitution);
void setFixtureSensor(double fixture, bool sensor);
void setFixtureFilter(double fixture, double categoryBits, double maskBits, double groupIndex);
bool testPoint(double fixture, double x, double y);
double createDistanceJoint(double bodyA, double bodyB, double anchorAX, double anchorAY, double anchorBX, double anchorBY, bool collideConnected);
void setDistanceJoint(double joint, double length, double minLength, double maxLength, double stiffness, double damping);
double createRevoluteJoint(double bodyA, double bodyB, double anchorX, double anchorY, bool collideConnected);
void setRevoluteJointMotor(double joint, bool enabled, double speed, double maxTorque);
void setRevoluteJointLimits(double joint, bool enabled, double lower, double upper);
double createWheelJoint(double bodyA, double bodyB, double anchorX, double anchorY, double axisX, double axisY, bool collideConnected);
void setWheelJointMotor(double joint, bool enabled, double speed, double maxTorque);
void setWheelJointLimits(double joint, bool enabled, double lower, double upper);
void setWheelJointSuspension(double joint, double stiffness, double damping);
double createMouseJoint(double bodyA, double bodyB, double anchorX, double anchorY, double maxForce, double stiffness, double damping);
void setMouseJointTarget(double joint, double x, double y);
void destroyJoint(double joint);
RefCollection* getContacts(double world);
RefCollection* queryAABB(double world, double minX, double minY, double maxX, double maxY);
RefCollection* rayCast(double world, double x1, double y1, double x2, double y2);
} // namespace box2d_native
