// Generated by tools/generate-bindings.py; do not edit.
// Internal primitive bindings; public functions in main.ts supply defaults and packing.
declare namespace box2dNative {

    //% shim=box2d::createWorld
    function createWorld(gravityX: number, gravityY: number): number;

    //% shim=box2d::destroyWorld
    function destroyWorld(world: number): void;

    //% shim=box2d::isValid
    function isValid(handle: number): boolean;

    //% shim=box2d::setGravity
    function setGravity(world: number, x: number, y: number): void;

    //% shim=box2d::step
    function step(world: number, seconds: number, velocityIterations: number, positionIterations: number): void;

    //% shim=box2d::setWorldSleepingAllowed
    function setWorldSleepingAllowed(world: number, allowed: boolean): void;

    //% shim=box2d::createBody
    function createBody(args: number[]): number;

    //% shim=box2d::destroyBody
    function destroyBody(body: number): void;

    //% shim=box2d::getBodyState
    function getBodyState(body: number): number[];

    //% shim=box2d::readBodyTransform
    function readBodyTransform(body: number, output: number[]): void;

    //% shim=box2d::readBodyBoxVertices
    function readBodyBoxVertices(body: number, box: number[], view: number[], output: number[]): void;

    //% shim=box2d::setTransform
    function setTransform(body: number, x: number, y: number, angle: number): void;

    //% shim=box2d::setLinearVelocity
    function setLinearVelocity(body: number, x: number, y: number): void;

    //% shim=box2d::setAngularVelocity
    function setAngularVelocity(body: number, velocity: number): void;

    //% shim=box2d::setBodyType
    function setBodyType(body: number, type: number): void;

    //% shim=box2d::setDamping
    function setDamping(body: number, linear: number, angular: number): void;

    //% shim=box2d::setGravityScale
    function setGravityScale(body: number, scale: number): void;

    //% shim=box2d::setBodyFlag
    function setBodyFlag(body: number, flag: number, enabled: boolean): void;

    //% shim=box2d::getBodyFlag
    function getBodyFlag(body: number, flag: number): boolean;

    //% shim=box2d::applyForce
    function applyForce(args: number[]): void;

    //% shim=box2d::applyForceToCenter
    function applyForceToCenter(body: number, x: number, y: number, wake: boolean): void;

    //% shim=box2d::applyLinearImpulse
    function applyLinearImpulse(args: number[]): void;

    //% shim=box2d::applyLinearImpulseToCenter
    function applyLinearImpulseToCenter(body: number, x: number, y: number, wake: boolean): void;

    //% shim=box2d::applyTorque
    function applyTorque(body: number, torque: number, wake: boolean): void;

    //% shim=box2d::applyAngularImpulse
    function applyAngularImpulse(body: number, impulse: number, wake: boolean): void;

    //% shim=box2d::getWorldPoint
    function getWorldPoint(body: number, x: number, y: number): number[];

    //% shim=box2d::getLocalPoint
    function getLocalPoint(body: number, x: number, y: number): number[];

    //% shim=box2d::createCircleShape
    function createCircleShape(radius: number, centerX: number, centerY: number): number;

    //% shim=box2d::createBoxShape
    function createBoxShape(args: number[]): number;

    //% shim=box2d::createPolygonShape
    function createPolygonShape(vertices: number[]): number;

    //% shim=box2d::createEdgeShape
    function createEdgeShape(x1: number, y1: number, x2: number, y2: number): number;

    //% shim=box2d::createChainShape
    function createChainShape(vertices: number[], loop: boolean): number;

    //% shim=box2d::destroyShape
    function destroyShape(shape: number): void;

    //% shim=box2d::createFixture
    function createFixture(args: number[]): number;

    //% shim=box2d::destroyFixture
    function destroyFixture(fixture: number): void;

    //% shim=box2d::getFixtureBody
    function getFixtureBody(fixture: number): number;

    //% shim=box2d::setFixtureMaterial
    function setFixtureMaterial(fixture: number, density: number, friction: number, restitution: number): void;

    //% shim=box2d::setFixtureSensor
    function setFixtureSensor(fixture: number, sensor: boolean): void;

    //% shim=box2d::setFixtureFilter
    function setFixtureFilter(fixture: number, categoryBits: number, maskBits: number, groupIndex: number): void;

    //% shim=box2d::testPoint
    function testPoint(fixture: number, x: number, y: number): boolean;

    //% shim=box2d::createDistanceJoint
    function createDistanceJoint(args: number[]): number;

    //% shim=box2d::setDistanceJoint
    function setDistanceJoint(args: number[]): void;

    //% shim=box2d::createRevoluteJoint
    function createRevoluteJoint(args: number[]): number;

    //% shim=box2d::setRevoluteJointMotor
    function setRevoluteJointMotor(joint: number, enabled: boolean, speed: number, maxTorque: number): void;

    //% shim=box2d::setRevoluteJointLimits
    function setRevoluteJointLimits(joint: number, enabled: boolean, lower: number, upper: number): void;

    //% shim=box2d::createWheelJoint
    function createWheelJoint(args: number[]): number;

    //% shim=box2d::setWheelJointMotor
    function setWheelJointMotor(joint: number, enabled: boolean, speed: number, maxTorque: number): void;

    //% shim=box2d::setWheelJointLimits
    function setWheelJointLimits(joint: number, enabled: boolean, lower: number, upper: number): void;

    //% shim=box2d::setWheelJointSuspension
    function setWheelJointSuspension(joint: number, stiffness: number, damping: number): void;

    //% shim=box2d::createMouseJoint
    function createMouseJoint(args: number[]): number;

    //% shim=box2d::setMouseJointTarget
    function setMouseJointTarget(joint: number, x: number, y: number): void;

    //% shim=box2d::destroyJoint
    function destroyJoint(joint: number): void;

    //% shim=box2d::getContacts
    function getContacts(world: number): number[];

    //% shim=box2d::queryAABB
    function queryAABB(args: number[]): number[];

    //% shim=box2d::rayCast
    function rayCast(args: number[]): number[];
}
