// Generated by tools/generate-bindings.py; do not edit.
// Internal primitive bindings; public functions in main.ts supply defaults and packing.
declare namespace box2dNativeShim {

    //% shim=box2dNative::createWorld
    function createWorld(gravityX: number, gravityY: number): number;

    //% shim=box2dNative::destroyWorld
    function destroyWorld(world: number): void;

    //% shim=box2dNative::isValid
    function isValid(handle: number): boolean;

    //% shim=box2dNative::setGravity
    function setGravity(world: number, x: number, y: number): void;

    //% shim=box2dNative::step
    function step(world: number, seconds: number, velocityIterations: number, positionIterations: number): void;

    //% shim=box2dNative::setWorldSleepingAllowed
    function setWorldSleepingAllowed(world: number, allowed: boolean): void;

    //% shim=box2dNative::createBody
    function createBody(args: number[]): number;

    //% shim=box2dNative::destroyBody
    function destroyBody(body: number): void;

    //% shim=box2dNative::getBodyState
    function getBodyState(body: number): number[];

    //% shim=box2dNative::readBodyTransform
    function readBodyTransform(body: number, output: number[]): void;

    //% shim=box2dNative::readBodyBoxVertices
    function readBodyBoxVertices(body: number, box: number[], view: number[], output: number[]): void;

    //% shim=box2dNative::setTransform
    function setTransform(body: number, x: number, y: number, angle: number): void;

    //% shim=box2dNative::setLinearVelocity
    function setLinearVelocity(body: number, x: number, y: number): void;

    //% shim=box2dNative::setAngularVelocity
    function setAngularVelocity(body: number, velocity: number): void;

    //% shim=box2dNative::setBodyType
    function setBodyType(body: number, type: number): void;

    //% shim=box2dNative::setDamping
    function setDamping(body: number, linear: number, angular: number): void;

    //% shim=box2dNative::setGravityScale
    function setGravityScale(body: number, scale: number): void;

    //% shim=box2dNative::setBodyFlag
    function setBodyFlag(body: number, flag: number, enabled: boolean): void;

    //% shim=box2dNative::getBodyFlag
    function getBodyFlag(body: number, flag: number): boolean;

    //% shim=box2dNative::applyForce
    function applyForce(args: number[]): void;

    //% shim=box2dNative::applyForceToCenter
    function applyForceToCenter(body: number, x: number, y: number, wake: boolean): void;

    //% shim=box2dNative::applyLinearImpulse
    function applyLinearImpulse(args: number[]): void;

    //% shim=box2dNative::applyLinearImpulseToCenter
    function applyLinearImpulseToCenter(body: number, x: number, y: number, wake: boolean): void;

    //% shim=box2dNative::applyTorque
    function applyTorque(body: number, torque: number, wake: boolean): void;

    //% shim=box2dNative::applyAngularImpulse
    function applyAngularImpulse(body: number, impulse: number, wake: boolean): void;

    //% shim=box2dNative::getWorldPoint
    function getWorldPoint(body: number, x: number, y: number): number[];

    //% shim=box2dNative::getLocalPoint
    function getLocalPoint(body: number, x: number, y: number): number[];

    //% shim=box2dNative::createCircleShape
    function createCircleShape(radius: number, centerX: number, centerY: number): number;

    //% shim=box2dNative::createBoxShape
    function createBoxShape(args: number[]): number;

    //% shim=box2dNative::createPolygonShape
    function createPolygonShape(vertices: number[]): number;

    //% shim=box2dNative::createEdgeShape
    function createEdgeShape(x1: number, y1: number, x2: number, y2: number): number;

    //% shim=box2dNative::createChainShape
    function createChainShape(vertices: number[], loop: boolean): number;

    //% shim=box2dNative::destroyShape
    function destroyShape(shape: number): void;

    //% shim=box2dNative::createFixture
    function createFixture(args: number[]): number;

    //% shim=box2dNative::destroyFixture
    function destroyFixture(fixture: number): void;

    //% shim=box2dNative::getFixtureBody
    function getFixtureBody(fixture: number): number;

    //% shim=box2dNative::setFixtureMaterial
    function setFixtureMaterial(fixture: number, density: number, friction: number, restitution: number): void;

    //% shim=box2dNative::setFixtureSensor
    function setFixtureSensor(fixture: number, sensor: boolean): void;

    //% shim=box2dNative::setFixtureFilter
    function setFixtureFilter(fixture: number, categoryBits: number, maskBits: number, groupIndex: number): void;

    //% shim=box2dNative::testPoint
    function testPoint(fixture: number, x: number, y: number): boolean;

    //% shim=box2dNative::createDistanceJoint
    function createDistanceJoint(args: number[]): number;

    //% shim=box2dNative::setDistanceJoint
    function setDistanceJoint(args: number[]): void;

    //% shim=box2dNative::createRevoluteJoint
    function createRevoluteJoint(args: number[]): number;

    //% shim=box2dNative::setRevoluteJointMotor
    function setRevoluteJointMotor(joint: number, enabled: boolean, speed: number, maxTorque: number): void;

    //% shim=box2dNative::setRevoluteJointLimits
    function setRevoluteJointLimits(joint: number, enabled: boolean, lower: number, upper: number): void;

    //% shim=box2dNative::createWheelJoint
    function createWheelJoint(args: number[]): number;

    //% shim=box2dNative::setWheelJointMotor
    function setWheelJointMotor(joint: number, enabled: boolean, speed: number, maxTorque: number): void;

    //% shim=box2dNative::setWheelJointLimits
    function setWheelJointLimits(joint: number, enabled: boolean, lower: number, upper: number): void;

    //% shim=box2dNative::setWheelJointSuspension
    function setWheelJointSuspension(joint: number, stiffness: number, damping: number): void;

    //% shim=box2dNative::createMouseJoint
    function createMouseJoint(args: number[]): number;

    //% shim=box2dNative::setMouseJointTarget
    function setMouseJointTarget(joint: number, x: number, y: number): void;

    //% shim=box2dNative::destroyJoint
    function destroyJoint(joint: number): void;

    //% shim=box2dNative::getContacts
    function getContacts(world: number): number[];

    //% shim=box2dNative::queryAABB
    function queryAABB(args: number[]): number[];

    //% shim=box2dNative::rayCast
    function rayCast(args: number[]): number[];
}
