// Opt-in wrapper smoke checks. The low-level smoke test supplies check().
function runWrapperSmokeTests() {
    const wrappedWorld = new box2d.World()
    const wrappedGround = wrappedWorld.createBody(box2d.BodyType.Static, 0, 5)
    const wrappedGroundShape = box2d.Shape.box(10, 0.5)
    const wrappedFloor = wrappedGround.createFixture(wrappedGroundShape, 0)
    wrappedGroundShape.destroy()
    const wrappedBall = wrappedWorld.createBody(box2d.BodyType.Dynamic)
    const wrappedCircle = box2d.Shape.circle(0.5)
    const wrappedFixture = wrappedBall.createFixture(wrappedCircle)
    wrappedCircle.destroy()
    for (let i = 0; i < 240; ++i) wrappedWorld.step()
    const wrappedState = wrappedBall.getState()
    const transform = [0, 0, 0]
    wrappedBall.readTransform(transform)
    check(Math.abs(transform[1] - wrappedState.y) < 0.001, "wrapped reusable transform")
    const vertices = [0, 0, 0, 0, 0, 0, 0, 0]
    wrappedGround.readBoxVertices([1, 0.5, 0, 0], [8, 80, 60], vertices)
    check(vertices[0] == 72 && vertices[1] == 96, "wrapped integer box vertices")
    check(Math.abs(wrappedState.y - 4) < 0.02, "wrapped body rests on ground")
    check(wrappedState.mass > 0 && wrappedBall.mass > 0 && wrappedBall.inertia > 0, "wrapped mass")
    const wrappedPosition = wrappedBall.position
    wrappedPosition.y = 100
    check(wrappedBall.position.y < 5, "vector snapshots do not change physics")
    check(Math.abs(wrappedBall.linearVelocity.y) < 0.001, "wrapped velocity snapshot")
    check(wrappedFixture.body.handle == wrappedBall.handle, "wrapped fixture owner")
    const wrappedContacts = wrappedWorld.getContacts()
    check(wrappedContacts.length == 1, "wrapped contacts")
    check(wrappedContacts[0].fixtureA.valid && wrappedContacts[0].fixtureB.valid, "wrapped contact fixtures")
    const wrappedHit = wrappedWorld.rayCast(0, 0, 0, 10)
    check(wrappedHit != null && wrappedHit.fixture.handle == wrappedFixture.handle, "wrapped ray fixture")
    check(wrappedHit.point.y > 3 && wrappedHit.normal.y == -1 && wrappedHit.fraction > 0, "wrapped ray fields")
    check(wrappedWorld.rayCast(20, 0, 20, 10) == null, "wrapped ray miss")
    check(wrappedWorld.queryAABB(-1, 3, 1, 6).length == 2, "wrapped query")
    check(wrappedFixture.testPoint(0, 4), "wrapped point test")
    wrappedWorld.setGravity(0, 0)
    wrappedWorld.setSleepingAllowed(false)
    wrappedBall.setPosition(1, 2)
    wrappedBall.angle = 0.5
    check(Math.abs(wrappedBall.angle - 0.5) < 0.001, "wrapped angle setter")
    check(Math.abs(wrappedBall.position.x - 1) < 0.001, "angle setter preserves position")
    wrappedBall.setTransform(0, 0, 0)
    wrappedBall.setLinearVelocity(0.25, 0.5)
    wrappedBall.angularVelocity = 0.75
    check(Math.abs(wrappedBall.angularVelocity - 0.75) < 0.001, "wrapped angular velocity")
    wrappedBall.setType(box2d.BodyType.Dynamic)
    wrappedBall.setDamping(0.1, 0.2)
    wrappedBall.setGravityScale(0)
    wrappedBall.setFlag(box2d.BodyFlag.Bullet, true)
    check(wrappedBall.getFlag(box2d.BodyFlag.Bullet), "wrapped flag")
    wrappedBall.applyForce(1, 0, 0, 0)
    wrappedBall.applyForceToCenter(0, 1)
    wrappedBall.applyLinearImpulse(0.5, 0, 0, 0)
    wrappedBall.applyLinearImpulseToCenter(0, 0.5)
    wrappedBall.applyTorque(0.1)
    wrappedBall.applyAngularImpulse(0.2)
    const wrappedPoint = wrappedBall.getWorldPoint(1, 2)
    const wrappedLocal = wrappedBall.getLocalPoint(wrappedPoint.x, wrappedPoint.y)
    check(Math.abs(wrappedLocal.x - 1) < 0.001, "wrapped coordinate conversion")
    wrappedFixture.setMaterial(2, 0.3, 0.4)
    wrappedFixture.setSensor(true)
    wrappedFixture.setFilter()
    const wrappedPolygon = box2d.Shape.polygon([-1, -1, 1, -1, 0, 1])
    const wrappedEdge = box2d.Shape.edge(-1, 0, 1, 0)
    const wrappedChain = box2d.Shape.chain([-1, -1, 1, -1, 1, 1])
    wrappedPolygon.destroy()
    wrappedEdge.destroy()
    wrappedChain.destroy()
    const wrappedDistance = wrappedGround.createDistanceJoint(wrappedBall, 0, 5, 0, 0)
    wrappedDistance.configure(5, 4, 6, 2, 0.5)
    wrappedDistance.destroy()
    const wrappedHinge = wrappedGround.createRevoluteJoint(wrappedBall, 0, 0)
    wrappedHinge.setMotor(true, 0.5, 1)
    wrappedHinge.setLimits(true, -0.5, 0.5)
    const wrappedMouse = wrappedGround.createMouseJoint(wrappedBall, 0, 0, 100, 10, 1)
    wrappedMouse.setTarget(1, 1)
    wrappedMouse.destroy()
    wrappedFloor.destroy()
    wrappedGround.destroy()
    check(!wrappedHinge.valid, "destroying either body invalidates joint wrappers")
    const lowLevelBody = box2d.createBody(wrappedWorld.handle, box2d.BodyType.Dynamic)
    const bodyView = new box2d.Body(lowLevelBody)
    check(bodyView.valid, "wrap a low-level body")
    box2d.destroyBody(lowLevelBody)
    check(!bodyView.valid, "low-level destruction invalidates wrappers")
    const survivingShape = box2d.Shape.circle(0.25)
    wrappedWorld.destroy()
    check(!wrappedBall.valid && !wrappedFixture.valid && !wrappedWorld.valid, "world invalidates wrapper children")
    check(survivingShape.valid, "world does not own shape templates")
    survivingShape.destroy()
    console.log("Box2D wrapper smoke test passed")
}
