// Opt-in low-level smoke checks. Keep temporary references off the global heap roots.
function check(condition: boolean, message: string) {
    if (!condition) control.fail(message)
}
function runNativeSmokeTests() {
    const physicsWorld = box2d.createWorld()
    const groundBody = box2d.createBody(physicsWorld, box2d.BodyType.Static, 0, 5)
    const groundShape = box2d.createBoxShape(10, 0.5)
    const groundFixture = box2d.createFixture(groundBody, groundShape, 0)
    const ballBody = box2d.createBody(physicsWorld, box2d.BodyType.Dynamic)
    const ballShape = box2d.createCircleShape(0.5)
    const ballFixture = box2d.createFixture(ballBody, ballShape)
    box2d.destroyShape(groundShape)
    box2d.destroyShape(ballShape)
    for (let i = 0; i < 240; i++) {
        box2d.step(physicsWorld)
    }
    check(Math.abs(box2d.getBodyState(ballBody)[box2d.BodyState.Y] - 4) < 0.02, "ball rests on ground")
    const transform = [0, 0, 0]
    box2d.readBodyTransform(ballBody, transform)
    check(Math.abs(transform[1] - 4) < 0.02, "reusable body transform")
    const vertices = [0, 0, 0, 0, 0, 0, 0, 0]
    box2d.readBodyBoxVertices(groundBody, [1, 0.5, 0, 0], [8, 80, 60], vertices)
    check(vertices[0] == 72 && vertices[1] == 96 && vertices[4] == 88 && vertices[5] == 104, "integer box vertices")
    check(box2d.getContacts(physicsWorld).length == 2, "touching fixtures")
    check(box2d.rayCast(physicsWorld, 0, 0, 0, 10)[box2d.RayHit.Fixture] == ballFixture, "closest ray hit")
    check(box2d.queryAABB(physicsWorld, -1, 3, 1, 6).length == 2, "query fixtures")
    check(box2d.testPoint(ballFixture, 0, 4), "point in ball")
    check(box2d.getFixtureBody(ballFixture) == ballBody, "fixture owner")
    box2d.setGravity(physicsWorld, 0, 0)
    box2d.setWorldSleepingAllowed(physicsWorld, false)
    box2d.setBodyType(ballBody, box2d.BodyType.Dynamic)
    box2d.setTransform(ballBody, 0, 0, 0)
    box2d.setLinearVelocity(ballBody, 0.25, 0.5)
    box2d.setAngularVelocity(ballBody, 0.75)
    box2d.setDamping(ballBody, 0.1, 0.2)
    box2d.setGravityScale(ballBody, 0)
    box2d.setBodyFlag(ballBody, box2d.BodyFlag.Bullet, true)
    check(box2d.getBodyFlag(ballBody, box2d.BodyFlag.Bullet), "bullet flag")
    box2d.applyForce(ballBody, 1, 0, 0, 0)
    box2d.applyForceToCenter(ballBody, 0, 1)
    box2d.applyLinearImpulse(ballBody, 0.5, 0, 0, 0)
    box2d.applyLinearImpulseToCenter(ballBody, 0, 0.5)
    box2d.applyTorque(ballBody, 0.1)
    box2d.applyAngularImpulse(ballBody, 0.2)
    const point = box2d.getWorldPoint(ballBody, 1, 2)
    const localPoint = box2d.getLocalPoint(ballBody, point[0], point[1])
    check(Math.abs(localPoint[0] - 1) < 0.001, "local coordinate")
    box2d.setFixtureMaterial(ballFixture, 2, 0.3, 0.4)
    box2d.setFixtureSensor(ballFixture, true)
    box2d.setFixtureFilter(ballFixture)
    const polygonShape = box2d.createPolygonShape([-1, -1, 1, -1, 0, 1])
    const edgeShape = box2d.createEdgeShape(-1, 0, 1, 0)
    const chainShape = box2d.createChainShape([-1, -1, 1, -1, 1, 1], false)
    box2d.destroyShape(polygonShape)
    box2d.destroyShape(edgeShape)
    box2d.destroyShape(chainShape)
    const distanceJoint = box2d.createDistanceJoint(groundBody, ballBody, 0, 5, 0, 0)
    box2d.setDistanceJoint(distanceJoint, 5, 4, 6, 2, 0.5)
    box2d.destroyJoint(distanceJoint)
    const hingeJoint = box2d.createRevoluteJoint(groundBody, ballBody, 0, 0)
    box2d.setRevoluteJointMotor(hingeJoint, true, 0.5, 1)
    box2d.setRevoluteJointLimits(hingeJoint, true, -0.5, 0.5)
    const mouseJoint = box2d.createMouseJoint(groundBody, ballBody, 0, 0, 100, 10, 1)
    box2d.setMouseJointTarget(mouseJoint, 1, 1)
    box2d.destroyJoint(mouseJoint)
    box2d.destroyFixture(groundFixture)
    box2d.destroyBody(groundBody)
    check(!box2d.isValid(hingeJoint), "body destruction invalidates joints")
    box2d.destroyWorld(physicsWorld)
    check(!box2d.isValid(ballBody) && !box2d.isValid(ballFixture), "world destruction invalidates children")
    console.log("Box2D native smoke test passed")
}
