#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
sim="$root/sim"
vendor="$root/vendor/box2d-2.4.1"
wasm="$(mktemp "${TMPDIR:-/tmp}/box2d.XXXXXX.wasm")"
trap 'rm -f "$wasm"' EXIT

mapfile -t sources < <(find "$vendor/src" -name '*.cpp' -print | sort)
exports=(
    bx_result
    bx_createWorld bx_destroyWorld bx_isValid bx_setGravity bx_step bx_setWorldSleepingAllowed
    bx_createBody bx_destroyBody bx_getBodyState bx_readBodyTransform bx_readBodyBoxVertices
    bx_setTransform bx_setLinearVelocity bx_setAngularVelocity bx_setBodyType bx_setDamping
    bx_setGravityScale bx_setBodyFlag bx_getBodyFlag bx_applyForce bx_applyForceToCenter
    bx_applyLinearImpulse bx_applyLinearImpulseToCenter bx_applyTorque bx_applyAngularImpulse
    bx_getWorldPoint bx_getLocalPoint bx_createCircleShape bx_createBoxShape
    bx_createPolygonShape bx_createEdgeShape bx_createChainShape bx_destroyShape
    bx_createFixture bx_destroyFixture bx_getFixtureBody bx_setFixtureMaterial
    bx_setFixtureSensor bx_setFixtureFilter bx_testPoint bx_createDistanceJoint
    bx_setDistanceJoint bx_createRevoluteJoint bx_setRevoluteJointMotor
    bx_setRevoluteJointLimits bx_createWheelJoint bx_setWheelJointMotor
    bx_setWheelJointLimits bx_setWheelJointSuspension bx_createMouseJoint
    bx_setMouseJointTarget bx_destroyJoint bx_getContacts bx_queryAABB bx_rayCast malloc free
)
exported="$(printf '"_%s",' "${exports[@]}")"
exported="[${exported%,}]"

em++ -std=c++11 -O3 -flto -fno-exceptions \
    -I"$sim" -I"$vendor/include" -I"$vendor/src" \
    "$root/native.cpp" "$sim/bridge.cpp" "${sources[@]}" \
    -s STANDALONE_WASM=1 -s ALLOW_MEMORY_GROWTH=1 \
    -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
    -s "EXPORTED_FUNCTIONS=$exported" \
    --no-entry -o "$wasm"

python3 - "$wasm" "$sim/wasm.ts" <<'PY'
import base64
import pathlib
import sys

source = pathlib.Path(sys.argv[1])
target = pathlib.Path(sys.argv[2])
encoded = base64.b64encode(source.read_bytes()).decode("ascii")
lines = [encoded[i:i + 120] for i in range(0, len(encoded), 120)]
target.write_text(
    "// Generated by sim/build.sh; do not edit.\n"
    "namespace pxsim.box2dWasm {\n"
    "    export const base64 =\n"
    + "\n".join(f'        "{line}" +' for line in lines[:-1])
    + f'\n        "{lines[-1]}";\n'
    "}\n"
)
PY
