// Auto-generated. Do not edit.
declare const enum DAL {
    // built/codal/build/codal_extra_definitions.h
    DEVICE_COMPONENT_COUNT = 64,
    DEVICE_DMESG_BUFFER_SIZE = 4096,
    DEVICE_TAG = 1,
    // built/codal/libraries/codal-core/inc/core/CodalCompat.h
    // built/codal/libraries/codal-core/inc/core/CodalComponent.h
    DEVICE_ID_BUTTON_A = 1,
    DEVICE_ID_BUTTON_B = 2,
    DEVICE_ID_BUTTON_AB = 3,
    DEVICE_ID_BUTTON_RESET = 4,
    DEVICE_ID_ACCELEROMETER = 5,
    DEVICE_ID_COMPASS = 6,
    DEVICE_ID_DISPLAY = 7,
    DEVICE_ID_THERMOMETER = 8,
    DEVICE_ID_RADIO = 9,
    DEVICE_ID_RADIO_DATA_READY = 10,
    DEVICE_ID_MULTIBUTTON_ATTACH = 11,
    DEVICE_ID_SERIAL = 12,
    DEVICE_ID_GESTURE = 13,
    DEVICE_ID_SYSTEM_TIMER = 14,
    DEVICE_ID_SCHEDULER = 15,
    DEVICE_ID_COMPONENT = 16,
    DEVICE_ID_LIGHT_SENSOR = 17,
    DEVICE_ID_TOUCH_SENSOR = 18,
    DEVICE_ID_SYSTEM_DAC = 19,
    DEVICE_ID_SYSTEM_MICROPHONE = 20,
    DEVICE_ID_SYSTEM_LEVEL_DETECTOR = 21,
    DEVICE_ID_IO_P0 = 100,
    DEVICE_ID_MESSAGE_BUS_LISTENER = 1021,
    DEVICE_ID_NOTIFY_ONE = 1022,
    DEVICE_ID_NOTIFY = 1023,
    DEVICE_COMPONENT_RUNNING = 4096,
    DEVICE_COMPONENT_STATUS_SYSTEM_TICK = 8192,
    DEVICE_COMPONENT_STATUS_IDLE_TICK = 16384,
    DEVICE_COMPONENT_LISTENERS_CONFIGURED = 1,
    DEVICE_COMPONENT_EVT_SYSTEM_TICK = 1,
    // built/codal/libraries/codal-core/inc/core/CodalDevice.h
    // built/codal/libraries/codal-core/inc/core/CodalDmesg.h
    // built/codal/libraries/codal-core/inc/core/CodalFiber.h
    DEVICE_SCHEDULER_RUNNING = 1,
    DEVICE_SCHEDULER_IDLE = 2,
    DEVICE_FIBER_FLAG_FOB = 1,
    DEVICE_FIBER_FLAG_PARENT = 2,
    DEVICE_FIBER_FLAG_CHILD = 4,
    DEVICE_FIBER_FLAG_DO_NOT_PAGE = 8,
    DEVICE_SCHEDULER_EVT_TICK = 1,
    DEVICE_SCHEDULER_EVT_IDLE = 2,
    // built/codal/libraries/codal-core/inc/core/CodalHeapAllocator.h
    DEVICE_MAXIMUM_HEAPS = 2,
    DEVICE_HEAP_BLOCK_FREE = 2147483648,
    // built/codal/libraries/codal-core/inc/core/CodalListener.h
    MESSAGE_BUS_LISTENER_PARAMETERISED = 1,
    MESSAGE_BUS_LISTENER_METHOD = 2,
    MESSAGE_BUS_LISTENER_BUSY = 4,
    MESSAGE_BUS_LISTENER_REENTRANT = 8,
    MESSAGE_BUS_LISTENER_QUEUE_IF_BUSY = 16,
    MESSAGE_BUS_LISTENER_DROP_IF_BUSY = 32,
    MESSAGE_BUS_LISTENER_NONBLOCKING = 64,
    MESSAGE_BUS_LISTENER_URGENT = 128,
    MESSAGE_BUS_LISTENER_DELETING = 32768,
    // built/codal/libraries/codal-core/inc/core/CodalUSB.h
    GET_STATUS = 0,
    CLEAR_FEATURE = 1,
    SET_FEATURE = 3,
    SET_ADDRESS = 5,
    GET_DESCRIPTOR = 6,
    SET_DESCRIPTOR = 7,
    GET_CONFIGURATION = 8,
    SET_CONFIGURATION = 9,
    GET_INTERFACE = 10,
    SET_INTERFACE = 11,
    SYNCH_FRAME = 12,
    DIRECTION_OUT = 0,
    DIRECTION_IN = 1,
    USB_CONFIG_POWERED_MASK = 64,
    USB_CONFIG_BUS_POWERED = 128,
    USB_CONFIG_SELF_POWERED = 192,
    USB_CONFIG_REMOTE_WAKEUP = 32,
    USB_DEVICE_DESCRIPTOR_TYPE = 1,
    USB_CONFIGURATION_DESCRIPTOR_TYPE = 2,
    USB_STRING_DESCRIPTOR_TYPE = 3,
    USB_INTERFACE_DESCRIPTOR_TYPE = 4,
    USB_ENDPOINT_DESCRIPTOR_TYPE = 5,
    REQUEST_HOSTTODEVICE = 0,
    REQUEST_DEVICETOHOST = 128,
    REQUEST_DIRECTION = 128,
    REQUEST_STANDARD = 0,
    REQUEST_CLASS = 32,
    REQUEST_VENDOR = 64,
    REQUEST_TYPE = 96,
    REQUEST_DESTINATION = 31,
    REQUEST_DEVICE = 0,
    REQUEST_INTERFACE = 1,
    REQUEST_ENDPOINT = 2,
    REQUEST_OTHER = 3,
    REQUEST_GET_STATUS = 0,
    REQUEST_CLEAR_FEATURE = 1,
    REQUEST_SET_FEATURE = 3,
    REQUEST_SYNCH_FRAME = 18,
    DEVICE_REMOTE_WAKEUP = 1,
    USB_EP_TYPE_CONTROL = 0,
    USB_EP_TYPE_ISOCHRONOUS = 1,
    USB_EP_TYPE_BULK = 2,
    USB_EP_TYPE_INTERRUPT = 3,
    // built/codal/libraries/codal-core/inc/core/ErrorNo.h
    DEVICE_OK = 0,
    DEVICE_INVALID_PARAMETER = -1001,
    DEVICE_NOT_SUPPORTED = -1002,
    DEVICE_CALIBRATION_IN_PROGRESS = -1003,
    DEVICE_CALIBRATION_REQUIRED = -1004,
    DEVICE_NO_RESOURCES = -1005,
    DEVICE_BUSY = -1006,
    DEVICE_CANCELLED = -1007,
    DEVICE_I2C_ERROR = -1010,
    DEVICE_SERIAL_IN_USE = -1011,
    DEVICE_NO_DATA = -1012,
    DEVICE_NOT_IMPLEMENTED = -1013,
    DEVICE_OOM = 20,
    DEVICE_HEAP_ERROR = 30,
    DEVICE_NULL_DEREFERENCE = 40,
    DEVICE_USB_ERROR = 50,
    // built/codal/libraries/codal-core/inc/core/EventModel.h
    // built/codal/libraries/codal-core/inc/core/MemberFunctionCallback.h
    // built/codal/libraries/codal-core/inc/core/NotifyEvents.h
    DEVICE_DISPLAY_EVT_FREE = 1,
    CODAL_SERIAL_EVT_TX_EMPTY = 2,
    DEVICE_UART_S_EVT_TX_EMPTY = 3,
    DEVICE_NOTIFY_USER_EVENT_BASE = 1024,
    // built/codal/libraries/codal-core/inc/core/codal_target_hal.h
    // built/codal/libraries/codal-core/inc/drivers/AbstractButton.h
    DEVICE_BUTTON_EVT_DOWN = 1,
    DEVICE_BUTTON_EVT_UP = 2,
    DEVICE_BUTTON_EVT_CLICK = 3,
    DEVICE_BUTTON_EVT_LONG_CLICK = 4,
    DEVICE_BUTTON_EVT_HOLD = 5,
    DEVICE_BUTTON_EVT_DOUBLE_CLICK = 6,
    DEVICE_BUTTON_LONG_CLICK_TIME = 1000,
    DEVICE_BUTTON_HOLD_TIME = 1500,
    DEVICE_BUTTON_STATE = 1,
    DEVICE_BUTTON_STATE_HOLD_TRIGGERED = 2,
    DEVICE_BUTTON_STATE_CLICK = 4,
    DEVICE_BUTTON_STATE_LONG_CLICK = 8,
    DEVICE_BUTTON_SIGMA_MIN = 0,
    DEVICE_BUTTON_SIGMA_MAX = 12,
    DEVICE_BUTTON_SIGMA_THRESH_HI = 8,
    DEVICE_BUTTON_SIGMA_THRESH_LO = 2,
    DEVICE_BUTTON_DOUBLE_CLICK_THRESH = 50,
    DEVICE_BUTTON_SIMPLE_EVENTS = 0,
    DEVICE_BUTTON_ALL_EVENTS = 1,
    ACTIVE_LOW = 0,
    ACTIVE_HIGH = 1,
    // built/codal/libraries/codal-core/inc/drivers/AnalogSensor.h
    ANALOG_THRESHOLD_LOW = 1,
    ANALOG_THRESHOLD_HIGH = 2,
    ANALOG_SENSOR_UPDATE_NEEDED = 3,
    ANALOG_SENSOR_INITIALISED = 1,
    ANALOG_SENSOR_HIGH_THRESHOLD_PASSED = 2,
    ANALOG_SENSOR_LOW_THRESHOLD_PASSED = 4,
    ANALOG_SENSOR_LOW_THRESHOLD_ENABLED = 8,
    ANALOG_SENSOR_HIGH_THRESHOLD_ENABLED = 16,
    // built/codal/libraries/codal-core/inc/drivers/Button.h
    // built/codal/libraries/codal-core/inc/drivers/CapTouchButton.h
    CAP_TOUCH_BUTTON_CALIBRATION_PERIOD = 10,
    CAP_TOUCH_BUTTON_CALIBRATION_LINEAR_OFFSET = 100,
    CAP_TOUCH_BUTTON_CALIBRATION_PERCENTAGE_OFFSET = 30,
    CAP_TOUCH_BUTTON_SAMPLE_PERIOD = 50,
    CAP_TOUCH_BUTTON_CALIBRATING = 16,
    // built/codal/libraries/codal-core/inc/drivers/HID.h
    HID_REQUEST_GET_REPORT = 1,
    HID_REQUEST_GET_IDLE = 2,
    HID_REQUEST_GET_PROTOCOL = 3,
    HID_REQUEST_SET_REPORT = 9,
    HID_REQUEST_SET_IDLE = 10,
    HID_REQUEST_SET_PROTOCOL = 11,
    // built/codal/libraries/codal-core/inc/drivers/I2C.h
    // built/codal/libraries/codal-core/inc/drivers/LIS3DH.h
    ACCELEROMETER_IMU_DATA_VALID = 2,
    LIS3DH_DEFAULT_ADDR = 50,
    LIS3DH_STATUS_REG = 39,
    LIS3DH_STATUS_REG_AUX = 7,
    LIS3DH_OUT_X_L = 40,
    LIS3DH_OUT_X_H = 41,
    LIS3DH_OUT_Y_L = 42,
    LIS3DH_OUT_Y_H = 43,
    LIS3DH_OUT_Z_L = 44,
    LIS3DH_OUT_Z_H = 45,
    LIS3DH_WHOAMI = 15,
    LIS3DH_CTRL_REG0 = 30,
    LIS3DH_CTRL_REG1 = 32,
    LIS3DH_CTRL_REG2 = 33,
    LIS3DH_CTRL_REG3 = 34,
    LIS3DH_CTRL_REG4 = 35,
    LIS3DH_CTRL_REG5 = 36,
    LIS3DH_CTRL_REG6 = 37,
    LIS3DH_FIFO_CTRL_REG = 46,
    LIS3DH_FIFO_SRC_REG = 47,
    LIS3DH_INT1_CFG = 48,
    LIS3DH_INT1_SRC = 49,
    LIS3DH_INT1_THS = 50,
    LIS3DH_INT1_DURATION = 51,
    LIS3DH_INT2_CFG = 52,
    LIS3DH_INT2_SRC = 53,
    LIS3DH_INT2_THS = 54,
    LIS3DH_INT2_DURATION = 55,
    LIS3DH_WHOAMI_VAL = 51,
    LIS3DH_SAMPLE_RANGES = 4,
    LIS3DH_SAMPLE_RATES = 7,
    ACCELEROMETER_EVT_DATA_UPDATE = 1,
    ACCELEROMETER_EVT_NONE = 0,
    ACCELEROMETER_EVT_TILT_UP = 1,
    ACCELEROMETER_EVT_TILT_DOWN = 2,
    ACCELEROMETER_EVT_TILT_LEFT = 3,
    ACCELEROMETER_EVT_TILT_RIGHT = 4,
    ACCELEROMETER_EVT_FACE_UP = 5,
    ACCELEROMETER_EVT_FACE_DOWN = 6,
    ACCELEROMETER_EVT_FREEFALL = 7,
    ACCELEROMETER_EVT_3G = 8,
    ACCELEROMETER_EVT_6G = 9,
    ACCELEROMETER_EVT_8G = 10,
    ACCELEROMETER_EVT_SHAKE = 11,
    ACCELEROMETER_REST_TOLERANCE = 200,
    ACCELEROMETER_TILT_TOLERANCE = 200,
    ACCELEROMETER_FREEFALL_TOLERANCE = 400,
    ACCELEROMETER_SHAKE_TOLERANCE = 400,
    ACCELEROMETER_3G_TOLERANCE = 3072,
    ACCELEROMETER_6G_TOLERANCE = 6144,
    ACCELEROMETER_8G_TOLERANCE = 8192,
    ACCELEROMETER_GESTURE_DAMPING = 5,
    ACCELEROMETER_SHAKE_DAMPING = 10,
    ACCELEROMETER_SHAKE_RTX = 30,
    ACCELEROMETER_SHAKE_COUNT_THRESHOLD = 4,
    // built/codal/libraries/codal-core/inc/drivers/LevelDetector.h
    LEVEL_THRESHOLD_LOW = 1,
    LEVEL_THRESHOLD_HIGH = 2,
    LEVEL_DETECTOR_INITIALISED = 1,
    LEVEL_DETECTOR_HIGH_THRESHOLD_PASSED = 2,
    LEVEL_DETECTOR_LOW_THRESHOLD_PASSED = 4,
    LEVEL_DETECTOR_DEFAULT_WINDOW_SIZE = 128,
    // built/codal/libraries/codal-core/inc/drivers/LinearAnalogSensor.h
    // built/codal/libraries/codal-core/inc/drivers/MessageBus.h
    // built/codal/libraries/codal-core/inc/drivers/MultiButton.h
    MULTI_BUTTON_STATE_1 = 1,
    MULTI_BUTTON_STATE_2 = 2,
    MULTI_BUTTON_HOLD_TRIGGERED_1 = 4,
    MULTI_BUTTON_HOLD_TRIGGERED_2 = 8,
    MULTI_BUTTON_SUPRESSED_1 = 16,
    MULTI_BUTTON_SUPRESSED_2 = 32,
    MULTI_BUTTON_ATTACHED = 64,
    // built/codal/libraries/codal-core/inc/drivers/NonLinearAnalogSensor.h
    // built/codal/libraries/codal-core/inc/drivers/Pin.h
    IO_STATUS_DIGITAL_IN = 1,
    IO_STATUS_DIGITAL_OUT = 2,
    IO_STATUS_ANALOG_IN = 4,
    IO_STATUS_ANALOG_OUT = 8,
    IO_STATUS_TOUCH_IN = 16,
    IO_STATUS_EVENT_ON_EDGE = 32,
    IO_STATUS_EVENT_PULSE_ON_EDGE = 64,
    DEVICE_PIN_MAX_OUTPUT = 1023,
    DEVICE_PIN_MAX_SERVO_RANGE = 180,
    DEVICE_PIN_DEFAULT_SERVO_RANGE = 2000,
    DEVICE_PIN_DEFAULT_SERVO_CENTER = 1500,
    DEVICE_PIN_EVENT_NONE = 0,
    DEVICE_PIN_EVENT_ON_EDGE = 1,
    DEVICE_PIN_EVENT_ON_PULSE = 2,
    DEVICE_PIN_EVENT_ON_TOUCH = 3,
    DEVICE_PIN_EVT_RISE = 2,
    DEVICE_PIN_EVT_FALL = 3,
    DEVICE_PIN_EVT_PULSE_HI = 4,
    DEVICE_PIN_EVT_PULSE_LO = 5,
    PIN_CAPABILITY_DIGITAL = 1,
    PIN_CAPABILITY_ANALOG = 2,
    // built/codal/libraries/codal-core/inc/drivers/Serial.h
    CODAL_SERIAL_DEFAULT_BAUD_RATE = 115200,
    CODAL_SERIAL_DEFAULT_BUFFER_SIZE = 20,
    CODAL_SERIAL_EVT_DELIM_MATCH = 1,
    CODAL_SERIAL_EVT_HEAD_MATCH = 2,
    CODAL_SERIAL_EVT_RX_FULL = 3,
    CODAL_SERIAL_RX_IN_USE = 1,
    CODAL_SERIAL_TX_IN_USE = 2,
    CODAL_SERIAL_RX_BUFF_INIT = 4,
    CODAL_SERIAL_TX_BUFF_INIT = 8,
    ASYNC = 0,
    SYNC_SPINWAIT = 1,
    SYNC_SLEEP = 2,
    RxInterrupt = 0,
    TxInterrupt = 1,
    // built/codal/libraries/codal-core/inc/drivers/Synthesizer.h
    SYNTHESIZER_SAMPLE_RATE = 44100,
    TONE_WIDTH = 1024,
    // built/codal/libraries/codal-core/inc/drivers/Timer.h
    SYSTEM_CLOCK_INIT = 1,
    // built/codal/libraries/codal-core/inc/drivers/TouchButton.h
    TOUCH_BUTTON_CALIBRATION_PERIOD = 10,
    TOUCH_BUTTON_CALIBRATION_LINEAR_OFFSET = 2,
    TOUCH_BUTTON_CALIBRATION_PERCENTAGE_OFFSET = 5,
    TOUCH_BUTTON_CALIBRATING = 16,
    // built/codal/libraries/codal-core/inc/drivers/TouchSensor.h
    TOUCH_SENSOR_MAX_BUTTONS = 10,
    TOUCH_SENSOR_SAMPLE_PERIOD = 50,
    TOUCH_SENSE_SAMPLE_MAX = 1000,
    TOUCH_SENSOR_UPDATE_NEEDED = 1,
    // built/codal/libraries/codal-core/inc/platform/yotta_cfg_mappings.h
    // built/codal/libraries/codal-core/inc/types/CoordinateSystem.h
    RAW = 0,
    SIMPLE_CARTESIAN = 1,
    NORTH_EAST_DOWN = 2,
    NORTH_EAST_UP = 3,
    // built/codal/libraries/codal-core/inc/types/DataStream.h
    DATASTREAM_MAXIMUM_BUFFERS = 1,
    // built/codal/libraries/codal-core/inc/types/Event.h
    DEVICE_ID_ANY = 0,
    DEVICE_EVT_ANY = 0,
    CREATE_ONLY = 0,
    CREATE_AND_FIRE = 1,
    DEVICE_EVENT_DEFAULT_LAUNCH_MODE = 1,
    // built/codal/libraries/codal-core/inc/types/Image.h
    // built/codal/libraries/codal-core/inc/types/ManagedBuffer.h
    // built/codal/libraries/codal-core/inc/types/ManagedString.h
    // built/codal/libraries/codal-core/inc/types/ManagedType.h
    // built/codal/libraries/codal-core/inc/types/Matrix4.h
    // built/codal/libraries/codal-core/inc/types/RefCounted.h
    REF_TAG_STRING = 1,
    REF_TAG_BUFFER = 2,
    REF_TAG_IMAGE = 3,
    REF_TAG_USER = 32,
    // built/codal/libraries/codal-core/inc/types/list.h
    // built/codal/libraries/codal-mbed/inc/MbedI2C.h
    // built/codal/libraries/codal-mbed/inc/MbedPin.h
    // built/codal/libraries/codal-mbed/inc/MbedSerial.h
    // built/codal/libraries/codal-mbed/inc/MbedTimedInterruptIn.h
    // built/codal/libraries/codal-mbed/inc/MbedTimer.h
    TIMER_ONE_DEFAULT_PRECISION_US = 1,
    TIMER_ONE_PRESCALER_OPTIONS = 5,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/DynamicPwm.h
    DEVICE_DEFAULT_PWM_PERIOD = 20000,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/SAMD21DAC.h
    SAMD21DAC_DEFAULT_FREQUENCY = 44100,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/SAMD21DMAC.h
    DMA_DESCRIPTOR_ALIGNMENT = 16,
    DMA_DESCRIPTOR_COUNT = 4,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/SAMD21PDM.h
    SAMD21_PDM_BUFFER_SIZE = 256,
    SAMD21_START_UP_DELAY = 3,
    SAMD21_PDM_DATA_READY = 1,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/USB.h
    USB_MAX_PKT_SIZE = 64,
    USB_DEFAULT_PID = 9218,
    USB_DEFAULT_VID = 1003,
    USB_EP_FLAG_NO_AUTO_ZLP = 1,
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/common_includes.h
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/inc/neopixel.h
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/model/CircuitPlayground.h
    // built/codal/libraries/codal-samd21-mbed/CIRCUIT_PLAYGROUND/model/CircuitPlaygroundIO.h
    ID_PIN_A0 = 100,
    ID_PIN_A1 = 101,
    ID_PIN_A2 = 102,
    ID_PIN_A3 = 103,
    ID_PIN_A4 = 104,
    ID_PIN_A5 = 105,
    ID_PIN_A6 = 106,
    ID_PIN_A7 = 107,
    ID_PIN_LED = 119,
    ID_PIN_SPEAKER = 120,
    ID_PIN_THERMISTOR = 121,
    ID_PIN_LIGHTSENSOR = 122,
    ID_PIN_INT1 = 123,
    ID_PIN_BUTTONA = 124,
    ID_PIN_BUTTONB = 125,
    ID_PIN_BUTTONC = 126,
    ID_PIN_TOUCHDRIVE = 127,
    ID_PIN_MIC_DATA = 128,
    ID_PIN_MIC_CLOCK = 129,
    DEVICE_ID_BUTTON_C = 1024,
    // built/codal/libraries/codal-samd21-mbed/inc/adafruit_ptc.h
    // built/codal/libraries/codal-samd21-mbed/inc/conf_clocks.h
    // built/codal/libraries/codal-samd21-mbed/inc/device_fiber.h
    // built/codal/libraries/codal-samd21-mbed/inc/device_types.h
    // built/codal/libraries/codal-samd21-mbed/inc/samd21_ptc_component.h
    PTC_REG_CONTROLA = 1107315712,
    PTC_BIT_ENABLE = 2,
    PTC_BIT_RUNINSTBY = 4,
    PTC_REG_CONTROLB = 1107315713,
    PTC_BIT_SYNCFLAG = 128,
    PTC_REG_UNK4C04 = 1107315716,
    PTC_REG_CONTROLC = 1107315717,
    PTC_BIT_INIT = 1,
    PTC_REG_INTDISABLE = 1107315720,
    PTC_REG_INTENABLE = 1107315721,
    PTC_BIT_EOCINTEN = 1,
    PTC_BIT_WCOINTEN = 2,
    PTC_REG_INTFLAGS = 1107315722,
    PTC_BIT_EOCINTFLAG = 1,
    PTC_BIT_WCOINTFLAG = 2,
    PTC_REG_FREQCONTROL = 1107315724,
    PTC_BIT_FREQSPREADEN = 16,
    PTC_REG_SAMPLEDELAY_MASK = 15,
    PTC_REG_CONVCONTROL = 1107315725,
    PTC_BIT_CONVSTARTED = 128,
    PTC_REG_ADCACC_MASK = 7,
    PTC_REG_YSELECT_L = 1107315728,
    PTC_REG_YSELECT_H = 1107315729,
    PTC_REG_YENABLE_L = 1107315732,
    PTC_REG_YENABLE_H = 1107315733,
    PTC_REG_XSELECT_L = 1107315730,
    PTC_REG_XSELECT_H = 1107315731,
    PTC_REG_XENABLE_L = 1107315734,
    PTC_REG_XENABLE_H = 1107315735,
    PTC_REG_COMPCAPL = 1107315736,
    PTC_REG_COMPCAPH = 1107315737,
    PTC_REG_INTCAP = 1107315738,
    PTC_REG_SERIESRES = 1107315739,
    PTC_REG_CONVRESULT_L = 1107315740,
    PTC_REG_CONVRESULT_H = 1107315741,
    PTC_REG_BURSTMODE = 1107315744,
    PTC_REG_BURSTMODE_MASK = 240,
    PTC_BIT_CTSLOWPOWER = 4,
    PTC_REG_XYENABLE = 1107315734,
    PTC_BIT_XYENABLE = 2,
    PTC_REG_WCO_MODE = 1107315745,
    PTC_REG_WCO_MODE_MASK = 7,
    PTC_SET_WCO_THRESHHOLD_A_L = 1107315748,
    PTC_SET_WCO_THRESHHOLD_A_H = 1107315749,
    PTC_SET_WCO_THRESHHOLD_B_L = 1107315750,
    PTC_SET_WCO_THRESHHOLD_B_H = 1107315751,
    // built/codal/pxtapp/dmac.h
    // built/codal/pxtapp/hf2.h
    HF2_BUF_SIZE = 256,
    // built/codal/pxtapp/hf2dbg.h
    HF2DBG_H = 1,
    HF2_DBG_MAGIC_START = 4041976959,
    HF2_DBG_GET_GLOBAL_STATE = 1409050336,
    HF2_DBG_RESTART = 287358355,
    HF2_DBG_RESUME = 665147697,
    HF2_EV_DBG_PAUSED = 915601917,
    HF2_DBG_GET_STACK = 1888490768,
    // built/codal/pxtapp/pins.h
    CFG_PIN_ACCELEROMETER_INT = 1,
    CFG_PIN_ACCELEROMETER_SCL = 2,
    CFG_PIN_ACCELEROMETER_SDA = 3,
    CFG_PIN_BTN_A = 4,
    CFG_PIN_BTN_B = 5,
    CFG_PIN_BTN_SLIDE = 6,
    CFG_PIN_DOTSTAR_CLOCK = 7,
    CFG_PIN_DOTSTAR_DATA = 8,
    CFG_PIN_FLASH_CS = 9,
    CFG_PIN_FLASH_MISO = 10,
    CFG_PIN_FLASH_MOSI = 11,
    CFG_PIN_FLASH_SCK = 12,
    CFG_PIN_LED = 13,
    CFG_PIN_LIGHT = 14,
    CFG_PIN_MICROPHONE = 15,
    CFG_PIN_MIC_CLOCK = 16,
    CFG_PIN_MIC_DATA = 17,
    CFG_PIN_MISO = 18,
    CFG_PIN_MOSI = 19,
    CFG_PIN_NEOPIXEL = 20,
    CFG_PIN_RX = 21,
    CFG_PIN_RXLED = 22,
    CFG_PIN_SCK = 23,
    CFG_PIN_SCL = 24,
    CFG_PIN_SDA = 25,
    CFG_PIN_SPEAKER_AMP = 26,
    CFG_PIN_TEMPERATURE = 27,
    CFG_PIN_TX = 28,
    CFG_PIN_TXLED = 29,
    CFG_PIN_IR_OUT = 30,
    CFG_PIN_IR_IN = 31,
    DEV_NUM_PINS = 64,
    DEVICE_ID_BUTTON_SLIDE = 3000,
    DEVICE_ID_MICROPHONE = 3001,
    // built/codal/pxtapp/pxt.h
    PAGE_SIZE = 256,
    // built/codal/pxtapp/pxtbase.h
    PXT_REF_TAG_STRING = 1,
    PXT_REF_TAG_BUFFER = 2,
    PXT_REF_TAG_IMAGE = 3,
    PXT_REF_TAG_NUMBER = 32,
    PXT_REF_TAG_ACTION = 33,
    Int8LE = 1,
    UInt8LE = 2,
    Int16LE = 3,
    UInt16LE = 4,
    Int32LE = 5,
    Int8BE = 6,
    UInt8BE = 7,
    Int16BE = 8,
    UInt16BE = 9,
    Int32BE = 10,
    UInt32LE = 11,
    UInt32BE = 12,
    Float32LE = 13,
    Float64LE = 14,
    Float32BE = 15,
    Float64BE = 16,
    Undefined = 0,
    Boolean = 1,
    Number = 2,
    String = 3,
    Object = 4,
    Function = 5,
    // built/codal/pxtapp/pxtconfig.h
    PXT_VM = 0,
    // built/codal/pxtapp/pxtcore.h
    // built/codal/pxtapp/uf2format.h
    UF2FORMAT_H = 1,
    APP_START_ADDRESS = 8192,
    UF2_FLAG_NOFLASH = 1,
    // built/codal/pxtapp/uf2hid.h
    UF2_HID_H = 1,
    HF2_CMD_BININFO = 1,
    HF2_MODE_BOOTLOADER = 1,
    HF2_MODE_USERSPACE = 2,
    HF2_CMD_INFO = 2,
    HF2_CMD_RESET_INTO_APP = 3,
    HF2_CMD_RESET_INTO_BOOTLOADER = 4,
    HF2_CMD_START_FLASH = 5,
    HF2_CMD_WRITE_FLASH_PAGE = 6,
    HF2_CMD_CHKSUM_PAGES = 7,
    HF2_CMD_READ_WORDS = 8,
    HF2_CMD_WRITE_WORDS = 9,
    HF2_CMD_DMESG = 16,
    HF2_FLAG_SERIAL_OUT = 128,
    HF2_FLAG_SERIAL_ERR = 192,
    HF2_FLAG_CMDPKT_LAST = 64,
    HF2_FLAG_CMDPKT_BODY = 0,
    HF2_FLAG_MASK = 192,
    HF2_SIZE_MASK = 63,
    HF2_STATUS_OK = 0,
    HF2_STATUS_INVALID_CMD = 1,
}
